-- SAG — esquema PostgreSQL (Supabase)
-- Ejecutar en SQL Editor de Supabase o vía init automático al arrancar.

CREATE TABLE IF NOT EXISTS PRESUPUESTO (
  id SERIAL PRIMARY KEY,
  empresa TEXT NOT NULL CHECK (empresa IN ('GANADERA GUAVIYU', 'GANADERA CHIVILCOY')),
  fecha TEXT NOT NULL,
  codigo_proveedor TEXT,
  razon_social_proveedor TEXT,
  concepto TEXT NOT NULL,
  rubro TEXT NOT NULL,
  nro_factura TEXT,
  pesos DOUBLE PRECISION DEFAULT 0,
  dolares_usd DOUBLE PRECISION DEFAULT 0,
  reales DOUBLE PRECISION DEFAULT 0,
  tc_usd DOUBLE PRECISION DEFAULT 0,
  tc_reales DOUBLE PRECISION DEFAULT 0,
  saldo_usd DOUBLE PRECISION DEFAULT 0,
  nro_registro INTEGER UNIQUE,
  responsable_gasto TEXT NOT NULL DEFAULT '',
  sub_rubro TEXT NOT NULL DEFAULT '',
  funcionario_cedula TEXT NOT NULL DEFAULT '',
  observaciones TEXT NOT NULL DEFAULT '',
  ingresado_por_email TEXT NOT NULL DEFAULT '',
  ingresado_por_nombre TEXT NOT NULL DEFAULT '',
  creado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_presupuesto_empresa ON PRESUPUESTO(empresa);
CREATE INDEX IF NOT EXISTS idx_presupuesto_fecha ON PRESUPUESTO(fecha);
CREATE INDEX IF NOT EXISTS idx_presupuesto_rubro ON PRESUPUESTO(rubro);
CREATE INDEX IF NOT EXISTS idx_presupuesto_responsable ON PRESUPUESTO(responsable_gasto);
CREATE INDEX IF NOT EXISTS idx_presupuesto_sub_rubro ON PRESUPUESTO(sub_rubro);
CREATE INDEX IF NOT EXISTS idx_presupuesto_funcionario_cedula ON PRESUPUESTO(funcionario_cedula);
CREATE UNIQUE INDEX IF NOT EXISTS idx_presupuesto_nro_registro ON PRESUPUESTO(nro_registro);

CREATE TABLE IF NOT EXISTS PRESUPUESTO_REGISTRO_SEQ (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  ultimo INTEGER NOT NULL DEFAULT 0
);
INSERT INTO PRESUPUESTO_REGISTRO_SEQ (id, ultimo) VALUES (1, 0)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS PROVEEDORES (
  id SERIAL PRIMARY KEY,
  cod INTEGER NOT NULL UNIQUE,
  razon_social TEXT NOT NULL,
  rut TEXT DEFAULT '',
  direccion TEXT DEFAULT '',
  ciudad TEXT DEFAULT '',
  creado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_proveedores_cod ON PROVEEDORES(cod);
CREATE INDEX IF NOT EXISTS idx_proveedores_razon ON PROVEEDORES(razon_social);

CREATE TABLE IF NOT EXISTS DIVISAS_TC (
  id SERIAL PRIMARY KEY,
  fecha TEXT NOT NULL,
  par TEXT NOT NULL CHECK (par IN ('UYU_USD', 'BRL_USD')),
  valor DOUBLE PRECISION NOT NULL,
  UNIQUE (fecha, par)
);

CREATE TABLE IF NOT EXISTS PRECIOS_GANADO_ACG (
  id SERIAL PRIMARY KEY,
  anio INTEGER NOT NULL,
  semana INTEGER NOT NULL,
  fecha_desde TEXT NOT NULL,
  fecha_hasta TEXT NOT NULL,
  segmento TEXT NOT NULL DEFAULT 'GORDO' CHECK (segmento IN ('GORDO', 'REPOSICION')),
  categoria TEXT NOT NULL CHECK (categoria IN ('NOVILLO', 'VACA', 'VAQUILLONA', 'TERNERO', 'TERNERA', 'VACA_INVERNADA')),
  valor DOUBLE PRECISION NOT NULL,
  unidad TEXT NOT NULL DEFAULT 'USD_KG_CUARTA_BALANZA',
  fuente TEXT NOT NULL DEFAULT 'ACG',
  creado_en TIMESTAMPTZ DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (anio, semana, segmento, categoria)
);

CREATE TABLE IF NOT EXISTS PRECIOS_GANADO_ACG_SYNC (
  id SERIAL PRIMARY KEY,
  segmento TEXT NOT NULL DEFAULT 'GORDO' CHECK (segmento IN ('GORDO', 'REPOSICION')),
  anio INTEGER NOT NULL,
  semana INTEGER NOT NULL,
  fecha_desde TEXT NOT NULL,
  fecha_hasta TEXT NOT NULL,
  novillo DOUBLE PRECISION,
  vaca DOUBLE PRECISION,
  vaquillona DOUBLE PRECISION,
  ternero DOUBLE PRECISION,
  ternera DOUBLE PRECISION,
  vaca_invernada DOUBLE PRECISION,
  resultado TEXT NOT NULL CHECK (resultado IN ('insertado', 'actualizado', 'sin_cambios', 'error')),
  detalle TEXT NOT NULL DEFAULT '',
  creado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_precios_ganado_fecha_hasta ON PRECIOS_GANADO_ACG(fecha_hasta DESC);
CREATE INDEX IF NOT EXISTS idx_precios_ganado_segmento ON PRECIOS_GANADO_ACG(segmento, fecha_hasta DESC);
CREATE INDEX IF NOT EXISTS idx_precios_ganado_sync_creado ON PRECIOS_GANADO_ACG_SYNC(creado_en DESC);

CREATE TABLE IF NOT EXISTS RUBROS (
  id SERIAL PRIMARY KEY,
  nombre TEXT NOT NULL,
  activo INTEGER NOT NULL DEFAULT 1,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_rubros_nombre ON RUBROS (LOWER(nombre));

CREATE TABLE IF NOT EXISTS SUB_RUBROS (
  id SERIAL PRIMARY KEY,
  nombre TEXT NOT NULL,
  grupo TEXT NOT NULL DEFAULT '',
  activo INTEGER NOT NULL DEFAULT 1,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sub_rubros_nombre ON SUB_RUBROS (LOWER(nombre));

CREATE TABLE IF NOT EXISTS SUB_RUBRO_ITEMS (
  id SERIAL PRIMARY KEY,
  sub_rubro_id INTEGER NOT NULL REFERENCES SUB_RUBROS(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  activo INTEGER NOT NULL DEFAULT 1,
  UNIQUE (sub_rubro_id, nombre)
);

CREATE TABLE IF NOT EXISTS RUBRO_SUB_RUBROS (
  rubro_id INTEGER NOT NULL REFERENCES RUBROS(id) ON DELETE CASCADE,
  sub_rubro_id INTEGER NOT NULL REFERENCES SUB_RUBROS(id) ON DELETE CASCADE,
  PRIMARY KEY (rubro_id, sub_rubro_id)
);

CREATE TABLE IF NOT EXISTS GRUPO_ICONOS (
  id SERIAL PRIMARY KEY,
  grupo TEXT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'imagen',
  archivo TEXT NOT NULL DEFAULT '',
  actualizado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_grupo_iconos_grupo ON GRUPO_ICONOS (LOWER(grupo));

CREATE TABLE IF NOT EXISTS RESPONSABLES (
  id SERIAL PRIMARY KEY,
  nombre TEXT NOT NULL,
  activo INTEGER NOT NULL DEFAULT 1,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_responsables_nombre ON RESPONSABLES (LOWER(nombre));

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
  id SERIAL PRIMARY KEY,
  cedula TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  apellido TEXT NOT NULL,
  domicilio TEXT NOT NULL DEFAULT '',
  ciudad TEXT NOT NULL DEFAULT '',
  departamento TEXT NOT NULL DEFAULT '',
  banco TEXT NOT NULL DEFAULT '',
  sucursal TEXT NOT NULL DEFAULT '',
  cuenta TEXT NOT NULL DEFAULT '',
  tipo_cuenta TEXT NOT NULL DEFAULT '',
  titular_cuenta TEXT NOT NULL DEFAULT '',
  celular TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  activo INTEGER NOT NULL DEFAULT 1,
  creado_en TIMESTAMPTZ DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_funcionarios_cedula ON FUNCIONARIOS(cedula);
CREATE INDEX IF NOT EXISTS idx_funcionarios_apellido ON FUNCIONARIOS(apellido);
CREATE INDEX IF NOT EXISTS idx_funcionarios_activo ON FUNCIONARIOS(activo);

CREATE TABLE IF NOT EXISTS INGRESOS_VENTAS (
  id SERIAL PRIMARY KEY,
  nro_registro INTEGER UNIQUE,
  fecha TEXT NOT NULL,
  codigo_proveedor TEXT NOT NULL DEFAULT '',
  razon_social_proveedor TEXT NOT NULL DEFAULT '',
  concepto TEXT NOT NULL,
  nro_factura TEXT NOT NULL DEFAULT '',
  pesos DOUBLE PRECISION NOT NULL DEFAULT 0,
  dolares_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
  tc_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
  total_usd DOUBLE PRECISION NOT NULL DEFAULT 0,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ventas_fecha ON INGRESOS_VENTAS(fecha);
CREATE INDEX IF NOT EXISTS idx_ventas_nro_registro ON INGRESOS_VENTAS(nro_registro);

CREATE TABLE IF NOT EXISTS INGRESOS_VENTAS_SEQ (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  ultimo INTEGER NOT NULL DEFAULT 0
);
INSERT INTO INGRESOS_VENTAS_SEQ (id, ultimo) VALUES (1, 0)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS VENTA_SUB_RUBROS (
  id SERIAL PRIMARY KEY,
  nombre TEXT NOT NULL,
  grupo TEXT NOT NULL DEFAULT '',
  activo INTEGER NOT NULL DEFAULT 1,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_venta_sub_rubros_nombre ON VENTA_SUB_RUBROS (LOWER(nombre));

CREATE TABLE IF NOT EXISTS VENTA_SUB_RUBRO_ITEMS (
  id SERIAL PRIMARY KEY,
  sub_rubro_id INTEGER NOT NULL REFERENCES VENTA_SUB_RUBROS(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  activo INTEGER NOT NULL DEFAULT 1,
  UNIQUE (sub_rubro_id, nombre)
);

CREATE TABLE IF NOT EXISTS VENTA_GRUPO_ICONOS (
  id SERIAL PRIMARY KEY,
  grupo TEXT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'imagen',
  archivo TEXT NOT NULL DEFAULT '',
  actualizado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_venta_grupo_iconos_grupo ON VENTA_GRUPO_ICONOS (LOWER(grupo));

CREATE TABLE IF NOT EXISTS STOCK_GANADERO_LOTE (
  id SERIAL PRIMARY KEY,
  nombre_archivo TEXT NOT NULL DEFAULT '',
  filas INTEGER NOT NULL DEFAULT 0,
  importado_en TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS STOCK_GANADERO_REGISTRO (
  id SERIAL PRIMARY KEY,
  lote_id INTEGER NOT NULL REFERENCES STOCK_GANADERO_LOTE(id) ON DELETE CASCADE,
  eid TEXT NOT NULL,
  vid TEXT NOT NULL DEFAULT '',
  fecha TEXT NOT NULL,
  hora TEXT NOT NULL DEFAULT '',
  condicion TEXT NOT NULL DEFAULT '',
  creado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_stock_reg_lote ON STOCK_GANADERO_REGISTRO(lote_id);
CREATE INDEX IF NOT EXISTS idx_stock_reg_eid ON STOCK_GANADERO_REGISTRO(eid);
CREATE INDEX IF NOT EXISTS idx_stock_reg_fecha ON STOCK_GANADERO_REGISTRO(fecha);

CREATE TABLE IF NOT EXISTS STOCK_GANADERO_DISPOSITIVO (
  clave TEXT PRIMARY KEY,
  eid TEXT NOT NULL DEFAULT '',
  sexo TEXT NOT NULL DEFAULT '',
  edad INTEGER,
  nacimiento_mes INTEGER,
  nacimiento_anio INTEGER,
  observaciones TEXT NOT NULL DEFAULT '',
  empresa TEXT NOT NULL DEFAULT '',
  grupo TEXT NOT NULL DEFAULT '',
  grupo_libre TEXT NOT NULL DEFAULT '',
  estado TEXT NOT NULL DEFAULT '',
  tipo_baja TEXT NOT NULL DEFAULT '',
  numero_guia TEXT NOT NULL DEFAULT '',
  baja_mes INTEGER,
  baja_anio INTEGER,
  actualizado_en TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS STOCK_GANADERO_DISPOSITIVO_HISTORIAL (
  id SERIAL PRIMARY KEY,
  clave TEXT NOT NULL,
  campo TEXT NOT NULL,
  etiqueta TEXT NOT NULL DEFAULT '',
  valor_anterior TEXT NOT NULL DEFAULT '',
  valor_nuevo TEXT NOT NULL DEFAULT '',
  creado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_stock_disp_hist_clave ON STOCK_GANADERO_DISPOSITIVO_HISTORIAL(clave);
CREATE INDEX IF NOT EXISTS idx_stock_disp_hist_fecha ON STOCK_GANADERO_DISPOSITIVO_HISTORIAL(creado_en);

CREATE TABLE IF NOT EXISTS STOCK_GANADERO_AUDITORIA_MOVIMIENTO (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES USERS(id) ON DELETE SET NULL,
  user_email TEXT NOT NULL DEFAULT '',
  user_nombre TEXT NOT NULL DEFAULT '',
  tipo TEXT NOT NULL,
  clave TEXT NOT NULL DEFAULT '',
  cantidad INTEGER NOT NULL DEFAULT 1,
  resumen TEXT NOT NULL DEFAULT '',
  detalle TEXT NOT NULL DEFAULT '',
  ip TEXT NOT NULL DEFAULT '',
  creado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_stock_audit_mov_user ON STOCK_GANADERO_AUDITORIA_MOVIMIENTO(user_id);
CREATE INDEX IF NOT EXISTS idx_stock_audit_mov_creado ON STOCK_GANADERO_AUDITORIA_MOVIMIENTO(creado_en DESC);
CREATE INDEX IF NOT EXISTS idx_stock_audit_mov_tipo ON STOCK_GANADERO_AUDITORIA_MOVIMIENTO(tipo);

CREATE TABLE IF NOT EXISTS USERS (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  nombre TEXT NOT NULL,
  rol TEXT NOT NULL CHECK (rol IN ('admin', 'editor', 'gestor_n2', 'consulta')),
  activo INTEGER NOT NULL DEFAULT 1,
  creado_en TIMESTAMPTZ DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ DEFAULT NOW(),
  ultimo_acceso TIMESTAMPTZ,
  failed_login_attempts INTEGER NOT NULL DEFAULT 0,
  locked_until TIMESTAMPTZ,
  avatar_tipo TEXT NOT NULL DEFAULT 'iniciales',
  avatar_archivo TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON USERS (LOWER(email));

CREATE TABLE IF NOT EXISTS USER_SESSIONS (
  id TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
  creado_en TIMESTAMPTZ DEFAULT NOW(),
  expira_en TIMESTAMPTZ NOT NULL,
  ip TEXT,
  user_agent TEXT
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON USER_SESSIONS(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expira ON USER_SESSIONS(expira_en);

CREATE TABLE IF NOT EXISTS AUTH_AUDIT_LOG (
  id SERIAL PRIMARY KEY,
  evento TEXT NOT NULL,
  email TEXT,
  ip TEXT,
  user_agent TEXT,
  detalle TEXT,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_auth_audit_creado ON AUTH_AUDIT_LOG(creado_en);

CREATE TABLE IF NOT EXISTS CHAT_MESSAGES (
  id SERIAL PRIMARY KEY,
  sender_id INTEGER NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
  recipient_id INTEGER NOT NULL DEFAULT 0,
  body TEXT NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  attachment_tipo TEXT,
  attachment_nombre TEXT,
  attachment_mime TEXT,
  attachment_tamano INTEGER,
  attachment_archivo TEXT
);
CREATE INDEX IF NOT EXISTS idx_chat_messages_general ON CHAT_MESSAGES(creado_en DESC);
CREATE INDEX IF NOT EXISTS idx_chat_messages_dm ON CHAT_MESSAGES(sender_id, recipient_id, creado_en DESC);

CREATE TABLE IF NOT EXISTS CHAT_READ_STATE (
  user_id INTEGER NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
  peer_id INTEGER NOT NULL DEFAULT 0,
  last_read_message_id INTEGER NOT NULL DEFAULT 0,
  actualizado_en TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, peer_id)
);

CREATE TABLE IF NOT EXISTS CHAT_WALLPAPER (
  user_id INTEGER NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
  peer_id INTEGER NOT NULL DEFAULT 0,
  wallpaper_id TEXT NOT NULL DEFAULT 'default',
  actualizado_en TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, peer_id)
);

CREATE TABLE IF NOT EXISTS CHAT_CHANNELS (
  id SERIAL PRIMARY KEY,
  nombre TEXT NOT NULL,
  peer_id INTEGER NOT NULL UNIQUE,
  es_sistema INTEGER NOT NULL DEFAULT 0,
  creado_por INTEGER REFERENCES USERS(id) ON DELETE SET NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizado_en TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS CHAT_CHANNEL_MEMBERS (
  channel_id INTEGER NOT NULL REFERENCES CHAT_CHANNELS(id) ON DELETE CASCADE,
  user_id INTEGER NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
  PRIMARY KEY (channel_id, user_id)
);

CREATE TABLE IF NOT EXISTS ROLE_ESCRITURA (
  rol TEXT PRIMARY KEY CHECK (rol IN ('admin', 'editor', 'consulta')),
  puede_escribir INTEGER NOT NULL DEFAULT 0,
  actualizado_en TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS ROLE_PERMISOS (
  rol TEXT NOT NULL CHECK (rol IN ('admin', 'editor', 'gestor_n2', 'consulta')),
  modulo TEXT NOT NULL,
  acceso INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (rol, modulo)
);

CREATE TABLE IF NOT EXISTS scg_schema_version (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  version INTEGER NOT NULL DEFAULT 1
);
INSERT INTO scg_schema_version (id, version) VALUES (1, 1)
ON CONFLICT (id) DO NOTHING;
