/** Fórmulas / principios activos frecuentes en tratamientos de ganado (sugerencias). */
export const FORMULAS_REMEDIO_GANADO: readonly string[] = [
  "Abamectina 1%",
  "Albendazol 2,5%",
  "Albendazol 10%",
  "Albendazol 25%",
  "Albendazol 10% + Cobre 0,5%",
  "Amprolio 9,6%",
  "Azaperona 2%",
  "Benzoato de albendazol 10%",
  "Betametasona 0,5 mg/ml",
  "Bromhexina 3%",
  "Buprenorfina 0,3 mg/ml",
  "Butafosfán 10% + Cianocobalamina 0,005%",
  "Carbetocina 0,15 mg/ml",
  "Ceftiofur sódico 2,2%",
  "Ceftiofur cristalino 6%",
  "Cloprostenol 0,075 mg/ml",
  "Clorsulon 15%",
  "Clostridium perfringens tipo D — toxoide",
  "Clostridium septicum — bacterina",
  "Dexametasona 2 mg/ml",
  "Diclazuril 2,5%",
  "Doramectina 0,5%",
  "Doramectina 1%",
  "Eprinomectina 0,5%",
  "Eprinomectina 1%",
  "Estradiol benzoato 1 mg/ml",
  "Estradiol cipionato 2 mg/ml",
  "Estradiol valerato 4 mg/ml",
  "Enrofloxacina 2,5%",
  "Enrofloxacina 5%",
  "Enrofloxacina 10%",
  "Espiramicina 10%",
  "Espiramicina 20%",
  "Fenbendazol 10%",
  "Fenbendazol 20%",
  "Florfenicol 20%",
  "Florfenicol 30%",
  "Flunixin meglumine 2,5%",
  "Flunixin meglumine 5%",
  "Formalina al 4% — vacuna antiaftosa",
  "Gentamicina 5%",
  "Gonadorelina 50 mcg/ml",
  "Hierro dextrano 20%",
  "Hierro dextrano 10%",
  "Ivermectina 0,2% L.A.",
  "Ivermectina 0,5% pour-on",
  "Ivermectina 1%",
  "Ivermectina 3,15%",
  "Ivermectina 1% + Clorsulon 10%",
  "Ivermectina 3,15% + Clorsulon 15%",
  "Ketoprofeno 1%",
  "Ketoprofeno 10%",
  "Levamisol 7,5%",
  "Levamisol 10%",
  "Lidocaína 2%",
  "Meloxicam 0,5%",
  "Meloxicam 2%",
  "Metamizol sódico 50%",
  "Metamizol sódico 25%",
  "Metronidazol 5%",
  "Miconazole 2%",
  "Minociclina 10%",
  "Moxidectina 1%",
  "Moxidectina 2%",
  "Neomicina + Sulfadimidina",
  "Nitroxinil 34%",
  "Oxitetraciclina 5%",
  "Oxitetraciclina 10% L.A.",
  "Oxitetraciclina 20% L.A.",
  "Oxfendazol 4,5%",
  "Oxfendazol 9,06%",
  "Penicilina G benzatínica 300.000 UI/ml",
  "Penicilina G procainica 300.000 UI/ml",
  "Penicilina G + Estreptomicina",
  "Praziquantel 5%",
  "Progesterona 4%",
  "Rafoxanida 12%",
  "Rafoxanida 7,5%",
  "Rifampicina 5%",
  "Selenio 0,1% + Vitamina E",
  "Sulfadoxina + Trimetoprima",
  "Sulfametoxazol + Trimetoprima",
  "Tilmicosina 30%",
  "Tilosina 20%",
  "Tilosina 10%",
  "Toltrazuril 2,5%",
  "Toltrazuril 5%",
  "Triclabendazol 5%",
  "Triclabendazol 10%",
  "Triclabendazol 12%",
  "Tulatromicina 2,5%",
  "Vitamina A + D3 + E inyectable",
  "Vitamina B12 0,05%",
  "Vitamina E + Selenio inyectable",
  "Xilazina 2%",
  "Zilpaterol 4,8%",
].sort((a, b) => a.localeCompare(b, "es", { sensitivity: "base" }));

/** Fórmulas / principios activos frecuentes en medicina equina (sugerencias). */
export const FORMULAS_REMEDIO_EQUINO: readonly string[] = [
  "Acepromazina 1%",
  "Altrenogest 0,044%",
  "Altrenogest 2,2 mg/ml",
  "Bromhexina 3%",
  "Butafosfán 10% + Cianocobalamina 0,005%",
  "Ceftiofur cristalino 6%",
  "Ceftiofur sódico 2,2%",
  "Detomidina 1 mg/ml",
  "Detomidina 10 mg/ml gel oral",
  "Dexametasona 2 mg/ml",
  "Diclofenaco sódico 1%",
  "Encefalitis equina occidental — vacuna",
  "Encefalitis equina oriental — vacuna",
  "Enrofloxacina 2,5%",
  "Enrofloxacina 5%",
  "Fenbendazol 10% pasta oral",
  "Fenbendazol 20%",
  "Fenilbutazona 20%",
  "Firocoxib 57 mg",
  "Flunixin meglumine 2,5%",
  "Flunixin meglumine 5%",
  "Gentamicina 5%",
  "Hialuronato sódico 10 mg/ml",
  "Hierro dextrano 20%",
  "Influenza equina — vacuna inactivada",
  "Ivermectina 1%",
  "Ivermectina 1,87% pasta oral",
  "Ketoprofeno 1%",
  "Ketoprofeno 10%",
  "Lidocaína 2%",
  "Meloxicam 0,5%",
  "Meloxicam 2%",
  "Metronidazol 5%",
  "Moxidectina 1%",
  "Moxidectina 2% gel oral",
  "Omeprazol pasta oral",
  "Oxibendazol 10%",
  "Oxitetraciclina 10% L.A.",
  "Pamoato de pirantel 11,4% pasta oral",
  "Pamoato de pirantel 13,2%",
  "Penicilina G procainica 300.000 UI/ml",
  "Polisulfato de glicosaminoglicano 50 mg/ml",
  "Potomac horse fever — vacuna",
  "Praziquantel 14,02% + Ivermectina 1,87%",
  "Praziquantel 14,03% + Moxidectina 0,4%",
  "Progesterona 4%",
  "Ranitidina 15 mg/ml",
  "Rinoneumonitis equina — vacuna",
  "Romifidina 10 mg/ml",
  "Tétanos equino — toxoide",
  "Vitamina E + Selenio inyectable",
  "West Nile — vacuna inactivada",
  "Xilazina 2%",
].sort((a, b) => a.localeCompare(b, "es", { sensitivity: "base" }));

export type FormulaRemedioModulo = "ganadero" | "equino";

export function catalogoFormulasPorModulo(
  modulo: FormulaRemedioModulo
): readonly string[] {
  return modulo === "equino" ? FORMULAS_REMEDIO_EQUINO : FORMULAS_REMEDIO_GANADO;
}
