/** Motivos frecuentes de tratamiento o control sanitario en ganadería. */
export const MOTIVOS_CONTROL_SANITARIO: readonly string[] = [
  "Antiparasitario / desparasitación",
  "Vacunación",
  "Control sanitario rutinario",
  "Tratamiento respiratorio",
  "Mastitis",
  "Metritis / infección uterina",
  "Cojera / podología",
  "Diarrea",
  "Reproducción / sincronización",
  "Deficiencia mineral / vitamínica",
  "Prevención garrapatas / moscas",
  "Infección dérmica",
  "Fiebre / síndrome febril",
  "Post-operatorio / curación",
  "Anemia / desnutrición",
  "Absceso / infección localizada",
  "Oftalmía / problema ocular",
  "Retención de placenta",
  "Parto asistido / posparto",
  "Queratoconjuntivitis",
];
