import type { StockControlSanitarioProductoFichaInput } from "./stock-control-sanitario-db.js";
import fotosManifest from "./stock-control-sanitario-producto-fichas-fotos.json" with { type: "json" };
import { sanitizeProductoFichaFoto } from "./stock-producto-ficha-foto.js";

const FOTOS_BY_NOMBRE = fotosManifest as Record<string, string>;

export interface ProductoFichaSeed extends StockControlSanitarioProductoFichaInput {
  foto?: string;
}

export function productoFichaSlug(nombre: string): string {
  return nombre
    .toLocaleLowerCase("es-UY")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function productoFichaFotoPath(nombre: string): string {
  return `/productos-sanitarios/${productoFichaSlug(nombre)}.jpg`;
}

function joinLines(lines: readonly string[]): string {
  return lines.join("\n");
}

function buildFicha(ficha: Omit<ProductoFichaSeed, "foto">): ProductoFichaSeed {
  const candidata = FOTOS_BY_NOMBRE[ficha.nombre] ?? productoFichaFotoPath(ficha.nombre);
  return {
    ...ficha,
    foto: sanitizeProductoFichaFoto(candidata),
  };
}

export const PRODUCTO_FICHAS_SEED: readonly ProductoFichaSeed[] = [
  buildFicha({
    nombre: "Agrovet Market",
    laboratorio: "Agrovet Market, laboratorio veterinario latinoamericano con foco en producción animal.",
    principio_activo: "Línea multicomponente: lactonas macrocíclicas, benzimidazoles, antibióticos y antiinflamatorios.",
    presentacion: "Inyectables 1% y 3,15%, pour-on, soluciones orales, bolos y premixes.",
    via_administracion: "Subcutánea, intramuscular, oral y tópica según línea.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO DE LINEA (habitual 21 a 122 DIAS).",
    tiempo_espera_leche: "SEGUN PRODUCTO; varias formulaciones no autorizadas en vacas en ordeñe.",
    detalles_tecnicos: joinLines([
      "• Portafolio orientado a control parasitario, terapéutica respiratoria y soporte metabólico.",
      "• Incluye formulaciones de acción corta y prolongada para sistemas de cría y engorde.",
      "• Protocolos frecuentes: antiparasitarios estratégicos pre-servicio y post-destete.",
      "• Ajustar dosis por peso real y rotar familias para reducir presión de resistencia.",
      "• Conservar entre 15 y 30 C, protegido de luz directa.",
    ]),
    caracteristicas: "Laboratorio con presencia comercial en UY y red regional. Útil para planes sanitarios integrales de campo cuando se busca disponibilidad de varias moléculas y formas farmacéuticas bajo un mismo proveedor.",
  }),
  buildFicha({
    nombre: "Albex",
    laboratorio: "Marca antiparasitaria difundida en Cono Sur, comercializada por distintos laboratorios según país.",
    principio_activo: "Albendazol.",
    presentacion: "Suspensión oral 10% y pasta/gel oral.",
    via_administracion: "Oral.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "14 a 28 DIAS (segun concentracion y etiqueta local).",
    tiempo_espera_leche: "48 a 96 HORAS en formulaciones habilitadas; revisar rotulo.",
    detalles_tecnicos: joinLines([
      "• Composición base: albendazol, benzimidazol de amplio espectro.",
      "• Indicado para nematodos gastrointestinales y pulmonares; actividad sobre cestodos y fasciola adulta en dosis altas.",
      "• Dosis orientativa bovinos: 7,5 mg/kg; ajustar segun objetivo parasitario.",
      "• Recomendado en tratamientos estratégicos de otoño y preparto.",
      "• Agitar antes de usar y mantener envase bien cerrado.",
    ]),
    caracteristicas: "Producto habitual en UY, AR y BR por su costo/beneficio. Conveniente cuando se prioriza vía oral y cobertura de helmintos mixtos; evitar subdosificar para no acelerar resistencia.",
  }),
  buildFicha({
    nombre: "Albenil",
    laboratorio: "Marca comercial de antiparasitarios benzimidazólicos en la región.",
    principio_activo: "Albendazol.",
    presentacion: "Suspensión oral 10% y 11,36%; frascos multidosis.",
    via_administracion: "Oral.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "14 a 28 DIAS.",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS LECHERAS en varias presentaciones; validar etiqueta.",
    detalles_tecnicos: joinLines([
      "• Antihelmíntico benzimidazol con acción ovicida parcial.",
      "• Cubre nematodos digestivos, pulmonares y algunos cestodos.",
      "• Dosis usual bovinos: 7,5 mg/kg; para fasciola adulta puede requerir dosis mayor.",
      "• Planificar tratamiento con monitoreo de HPG para optimizar eficacia.",
      "• Conservar en lugar seco, sin congelar.",
    ]),
    caracteristicas: "Presencia comercial en UY/AR/BR. Opción frecuente para recría y ovinos; útil en rotación con lactonas y salicilanilidas en establecimientos con historial de resistencia.",
  }),
  buildFicha({
    nombre: "Aranda",
    laboratorio: "Aranda, laboratorio veterinario con foco productivo en Argentina.",
    principio_activo: "Línea de antiparasitarios, antibióticos y formulaciones minerales.",
    presentacion: "Inyectables, orales, tópicos y soluciones vitamínicas.",
    via_administracion: "SC, IM, oral y tópica según producto.",
    especie: "Bovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO DE LINEA (rango habitual 10 a 60 DIAS).",
    tiempo_espera_leche: "SEGUN PRODUCTO; revisar indicaciones de cada rótulo.",
    detalles_tecnicos: joinLines([
      "• Portafolio orientado a manejo sanitario de rodeos de cría e invernada.",
      "• Incluye antiparasitarios, antimicrobianos de uso inyectable y soporte nutricional.",
      "• Definir esquemas con criterio epidemiológico local y calendario reproductivo.",
      "• Reforzar buenas prácticas: agujas adecuadas, higiene y registro por lote.",
      "• Conservación estándar de productos veterinarios entre 15 y 30 C.",
    ]),
    caracteristicas: "Presencia principal en AR. Se utiliza cuando el campo busca oferta nacional con cobertura de terapéutica general de bovinos y reposición ágil en distribuidores locales.",
  }),
  buildFicha({
    nombre: "Ausmectin",
    laboratorio: "Marca comercial de endectocida en bovinos.",
    principio_activo: "Ivermectina (segun versión 1% o larga accion).",
    presentacion: "Inyectable SC 1% y formulaciones de mayor persistencia.",
    via_administracion: "Subcutánea.",
    especie: "Bovinos",
    tiempo_espera_carne: "35 a 122 DIAS (segun formulacion).",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS LECHERAS EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Endectocida activo frente a nematodos gastrointestinales y pulmonares.",
      "• Actividad adicional sobre ectoparásitos como piojos y ácaros sensibles.",
      "• Dosis típica 1%: 200 mcg/kg SC.",
      "• En formulaciones de larga acción, respetar manejo de retiro extendido.",
      "• Almacenar alejado de luz y no reutilizar frascos contaminados.",
    ]),
    caracteristicas: "Comercializado en UY/AR/BR. Útil en programas de desparasitación estratégica; conviene alternar con otras familias para sostener eficacia a campo.",
  }),
  buildFicha({
    nombre: "Bago",
    laboratorio: "Bagó, laboratorio con trayectoria en salud animal y humana en el Cono Sur.",
    principio_activo: "Líneas terapéuticas de antimicrobianos, antiparasitarios, antiinflamatorios y biológicos.",
    presentacion: "Inyectables, orales, tópicos y vacunas según unidad de negocio.",
    via_administracion: "IM, SC, oral y tópica según formulación.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO DE LINEA.",
    tiempo_espera_leche: "SEGUN PRODUCTO; hay moléculas aptas y no aptas para ordeñe.",
    detalles_tecnicos: joinLines([
      "• Portafolio para enfermedades respiratorias, digestivas, podales y control parasitario.",
      "• Incluye soluciones para rodeo de cría, tambo y feedlot.",
      "• Implementar protocolos con diagnóstico y antibiograma cuando corresponda.",
      "• Manejo responsable de antimicrobianos para minimizar resistencia.",
      "• Mantener cadena de conservación recomendada por etiqueta.",
    ]),
    caracteristicas: "Laboratorio de referencia en AR y UY con red técnica sólida. Adecuado para establecimientos que buscan integración entre prevención, tratamiento y soporte profesional continuo.",
  }),
  buildFicha({
    nombre: "Banamine",
    laboratorio: "MSD/Merck Animal Health según país.",
    principio_activo: "Flunixin meglumine.",
    presentacion: "Solución inyectable 50 mg/mL.",
    via_administracion: "Intravenosa lenta (preferente) o intramuscular según etiqueta.",
    especie: "Bovinos",
    tiempo_espera_carne: "4 a 8 DIAS (segun via y registro local).",
    tiempo_espera_leche: "36 HORAS aproximadas en formulaciones para tambo.",
    detalles_tecnicos: joinLines([
      "• AINE con potente efecto antiinflamatorio, analgésico y antipirético.",
      "• Indicaciones: endotoxemia, mastitis aguda, procesos respiratorios y dolor.",
      "• Dosis habitual: 1,1 a 2,2 mg/kg cada 24 h por corto periodo.",
      "• Evitar uso concomitante con otros AINE o nefrotóxicos.",
      "• Conservar a temperatura ambiente y respetar asepsia de aplicación.",
    ]),
    caracteristicas: "Muy usado en UY/AR/BR para cuadros febriles y dolor agudo. Buena herramienta de soporte, siempre junto con tratamiento etiológico cuando hay infección bacteriana.",
  }),
  buildFicha({
    nombre: "Baycox",
    laboratorio: "Elanco/Bayer histórico según mercado.",
    principio_activo: "Toltrazuril.",
    presentacion: "Suspensión oral 5% para terneros.",
    via_administracion: "Oral.",
    especie: "Bovinos",
    tiempo_espera_carne: "63 DIAS (valor de referencia frecuente).",
    tiempo_espera_leche: "NO USAR EN VACAS LECHERAS EN PRODUCCION.",
    detalles_tecnicos: joinLines([
      "• Anticoccidial triazinona con acción sobre múltiples estadios de Eimeria spp.",
      "• Uso metafiláctico en terneros de riesgo y tratamiento temprano clínico.",
      "• Dosis de referencia: 15 mg/kg en dosis única.",
      "• Complementar con manejo de cama, higiene y reducción de carga infectiva.",
      "• Guardar bien cerrado y agitar antes de administrar.",
    ]),
    caracteristicas: "Comercialización regional UY/AR/BR. Clave en recría intensiva y sistemas con antecedentes de coccidiosis clínica o subclínica que afecta ganancia diaria.",
  }),
  buildFicha({
    nombre: "Baymec",
    laboratorio: "Marca de endectocida de uso ganadero.",
    principio_activo: "Ivermectina.",
    presentacion: "Inyectable 1% y variantes de larga acción según país.",
    via_administracion: "Subcutánea.",
    especie: "Bovinos",
    tiempo_espera_carne: "35 a 122 DIAS.",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS LECHERAS.",
    detalles_tecnicos: joinLines([
      "• Lactona macrocíclica activa contra nematodos y ectoparásitos sensibles.",
      "• Dosis estándar 1%: 1 mL/50 kg (200 mcg/kg).",
      "• Seleccionar momento de aplicación según presión parasitaria estacional.",
      "• No aplicar más volumen por punto que el recomendado por etiqueta.",
      "• Conservar protegido de luz solar directa.",
    ]),
    caracteristicas: "Producto difundido en UY/AR/BR. Conveniente para planes de control integral en rodeos de cría, con monitoreo de eficacia antiparasitaria por establecimiento.",
  }),
  buildFicha({
    nombre: "Bectin",
    laboratorio: "Marca comercial de antiparasitario endectocida.",
    principio_activo: "Ivermectina (1% y presentaciones relacionadas).",
    presentacion: "Solución inyectable y en algunos mercados pour-on.",
    via_administracion: "SC y/o tópica según presentación.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "35 a 49 DIAS para 1%; mayor en formulaciones prolongadas.",
    tiempo_espera_leche: "NO USAR EN ORDEÑE salvo formulación autorizada.",
    detalles_tecnicos: joinLines([
      "• Endectocida para control de nematodes gastrointestinales y pulmonares.",
      "• Efecto sobre piojos y ácaros de importancia productiva.",
      "• Dosis orientativa inyectable: 200 mcg/kg.",
      "• Integrar con manejo de potreros y control de carga animal.",
      "• Mantener cadena de calidad del producto en depósito.",
    ]),
    caracteristicas: "Presente en UY, AR y BR. Se emplea en esquemas de rutina y estratégicos; recomendable ajustar calendario según clima, categoría y antecedentes parasitarios.",
  }),
  buildFicha({
    nombre: "Biogenesis Bagó",
    laboratorio: "Biogénesis Bagó, laboratorio líder regional en biológicos y salud ganadera.",
    principio_activo: "Líneas de vacunas clostridiales, reproductivas, respiratorias y antiparasitarios.",
    presentacion: "Vacunas inyectables, antiparasitarios inyectables/orales y complementos.",
    via_administracion: "SC, IM, oral y tópica según línea.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO; en vacunas generalmente 0 DIAS.",
    tiempo_espera_leche: "SEGUN PRODUCTO; revisar ficha técnica del biológico o fármaco.",
    detalles_tecnicos: joinLines([
      "• Fuerte enfoque en prevención: clostridiosis, complejos respiratorios y reproductivos.",
      "• Portafolio integrado para cría, recría y feedlot.",
      "• Requiere manejo estricto de cadena de frío en vacunas.",
      "• Protocolizar primovacunación y refuerzos por categoría.",
      "• Complementar con bioseguridad y trazabilidad de lotes.",
    ]),
    caracteristicas: "Amplia presencia en AR/UY/BR con soporte técnico a campo. Elección frecuente para programas preventivos de alto impacto sanitario y productivo.",
  }),
  buildFicha({
    nombre: "Boehringer Ingelheim",
    laboratorio: "Boehringer Ingelheim Animal Health, laboratorio líder global en bovinos.",
    principio_activo: "Líneas antiparasitarias, antimicrobianas y biológicos respiratorios/reproductivos.",
    presentacion: "Inyectables, pour-on, vacunas y soluciones orales.",
    via_administracion: "SC, IM, oral y tópica según producto.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO DE LINEA.",
    tiempo_espera_leche: "SEGUN PRODUCTO; validar etiqueta local.",
    detalles_tecnicos: joinLines([
      "• Portfolio de referencia para BRD, control de helmintos y ectoparásitos.",
      "• Incluye moléculas de alta persistencia y vacunas de uso estratégico.",
      "• El diseño de protocolos debe considerar categoría, estrés y estacionalidad.",
      "• Se recomienda capacitación de personal para correcta técnica de aplicación.",
      "• Almacenamiento según especificación de cada presentación.",
    ]),
    caracteristicas: "Comercialización consolidada en UY/AR/BR. Se utiliza en sistemas intensivos y extensivos por calidad farmacéutica y respaldo técnico internacional.",
  }),
  buildFicha({
    nombre: "Brouwer",
    laboratorio: "Brouwer, laboratorio veterinario de trayectoria en Argentina y Uruguay.",
    principio_activo: "Líneas antiparasitarias, antibióticas y antiinflamatorias.",
    presentacion: "Inyectables, orales y tópicos.",
    via_administracion: "IM, SC, oral y tópica según producto.",
    especie: "Bovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO DE LINEA.",
    tiempo_espera_leche: "SEGUN PRODUCTO; algunas formulaciones no aptas en ordeñe.",
    detalles_tecnicos: joinLines([
      "• Portafolio orientado a patología respiratoria y control de parásitos.",
      "• Presenta alternativas para cría y terminación.",
      "• Definir uso con diagnóstico y calendario sanitario del establecimiento.",
      "• Mantener registro de lote, dosis y operador para trazabilidad.",
      "• Conservación estándar: temperatura controlada y sin exposición solar.",
    ]),
    caracteristicas: "Presencia comercial en AR y UY. Marca elegida por disponibilidad local y variedad de soluciones para manejo sanitario integral de rodeo.",
  }),
  buildFicha({
    nombre: "Calier",
    laboratorio: "Calier, laboratorio de salud animal con desarrollo en rumiantes.",
    principio_activo: "Líneas antiparasitarias, antimicrobianas y suplementos.",
    presentacion: "Inyectables, orales, pour-on y polvos.",
    via_administracion: "SC, IM, oral y tópica según formulación.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO.",
    tiempo_espera_leche: "SEGUN PRODUCTO; revisar marbete de cada país.",
    detalles_tecnicos: joinLines([
      "• Portfolio para helmintos, enfermedades infecciosas y soporte nutricional.",
      "• Incluye formulaciones adaptadas a sistemas pastoriles e intensivos.",
      "• Programar tratamientos en base a riesgo y categoría productiva.",
      "• Reforzar control de resistencia antiparasitaria con monitoreo periódico.",
      "• Conservar en depósitos limpios, secos y ventilados.",
    ]),
    caracteristicas: "Laboratorio con cobertura AR/UY/BR. Útil cuando se busca proveedor multipropósito con presencia regional y asistencia técnica comercial.",
  }),
  buildFicha({
    nombre: "Ceva Salud Animal",
    laboratorio: "Ceva Salud Animal, laboratorio líder con fuerte enfoque en rumiantes.",
    principio_activo: "Líneas de vacunas, antimicrobianos, antiparasitarios y reproducción.",
    presentacion: "Vacunas inyectables, antibióticos, hormonales y antiparasitarios.",
    via_administracion: "SC, IM, oral y tópica según línea.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO DE LINEA.",
    tiempo_espera_leche: "SEGUN PRODUCTO; en vacunas generalmente 0 DIAS.",
    detalles_tecnicos: joinLines([
      "• Soluciones para prevención respiratoria, clostridial y reproductiva.",
      "• También ofrece terapias para dolor, infección y parasitosis.",
      "• Protocolizar uso según objetivo zootécnico y epidemiología local.",
      "• Mantener cadena de frío para biológicos y verificar fecha de vencimiento.",
      "• Promover uso prudente de antimicrobianos.",
    ]),
    caracteristicas: "Alta presencia en UY/AR/BR con respaldo técnico. Frecuente en campos que priorizan prevención y protocolos sanitarios estandarizados por categoría.",
  }),
  buildFicha({
    nombre: "Cobalt",
    laboratorio: "Marca comercial de suplementos y terapias minerales para rumiantes.",
    principio_activo: "Cobalto y/o combinaciones con vitamina B12 y oligoelementos.",
    presentacion: "Inyectable mineral y soluciones orales.",
    via_administracion: "Subcutánea, intramuscular u oral según versión.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "0 DIAS en suplementos minerales habituales.",
    tiempo_espera_leche: "0 DIAS.",
    detalles_tecnicos: joinLines([
      "• Formulación para corregir hipocobaltosis y apoyar metabolismo energético.",
      "• Indicada en rodeos con suelos deficientes y animales en estrés nutricional.",
      "• Dosis y frecuencia dependen del contenido elemental y estado corporal.",
      "• Puede integrarse con planes de suplementación mineral del establecimiento.",
      "• Almacenar en ambiente fresco y protegido de contaminación.",
    ]),
    caracteristicas: "Uso extendido en UY/AR/BR como apoyo de recría y vacas en servicio. Útil en planteos pastoriles donde se detectan deficiencias minerales de base.",
  }),
  buildFicha({
    nombre: "Cydectin",
    laboratorio: "Elanco (históricamente Fort Dodge/Pfizer en algunos mercados).",
    principio_activo: "Moxidectina.",
    presentacion: "Inyectable 1%, pour-on 0,5% y oral según país.",
    via_administracion: "SC, tópica y oral según formulación.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "14 a 42 DIAS (segun presentacion local).",
    tiempo_espera_leche: "NO AUTORIZADO EN ORDEÑE para varias formulaciones.",
    detalles_tecnicos: joinLines([
      "• Lactona macrocíclica de alta lipofilia y persistencia clínica.",
      "• Cubre nematodos gastrointestinales/pulmonares y ectoparásitos sensibles.",
      "• Dosis inyectable referencial: 200 mcg/kg.",
      "• Valiosa en rodeos con sensibilidad reducida a otras moléculas.",
      "• Conservar entre 15 y 30 C, evitando calor excesivo.",
    ]),
    caracteristicas: "Comercializada en UY/AR/BR. Herramienta estratégica para rotación antihelmíntica y manejo de resistencia, con buena persistencia en condiciones de campo.",
  }),
  buildFicha({
    nombre: "Dectomax",
    laboratorio: "Zoetis en la mayoría de mercados de la región.",
    principio_activo: "Doramectina 1%.",
    presentacion: "Inyectable SC 1% y pour-on según registro local.",
    via_administracion: "Subcutánea y tópica según presentación.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "49 a 50 DIAS (inyectable 1% referencia).",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS LECHERAS EN PRODUCCION.",
    detalles_tecnicos: joinLines([
      "• Endectocida macrocíclico para nematodos GI/pulmonares y parásitos externos.",
      "• Dosis estándar inyectable: 1 mL/50 kg de peso vivo.",
      "• Útil en programas estratégicos pre y post temporada de alta carga parasitaria.",
      "• Evitar subdosificación y ajustar por peso real del lote.",
      "• Conservar protegido de luz; no congelar.",
    ]),
    caracteristicas: "Producto de referencia en UY/AR/BR. Muy utilizado en cría e invernada por su eficacia y persistencia, siempre dentro de planes de manejo antiresistencia.",
  }),
  buildFicha({
    nombre: "Doramec",
    laboratorio: "Marca comercial de endectocida para bovinos.",
    principio_activo: "Doramectina.",
    presentacion: "Inyectable 1% y versiones tópicas en algunos mercados.",
    via_administracion: "Subcutánea y/o tópica.",
    especie: "Bovinos",
    tiempo_espera_carne: "35 a 49 DIAS (segun formulacion).",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS LECHERAS EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Lactona macrocíclica con acción sobre nematodos y ectoparásitos sensibles.",
      "• Dosis usual: 200 mcg/kg de peso vivo.",
      "• Indicado en tratamientos de otoño y pre-encierro en invernada.",
      "• Recomendable monitoreo de eficacia post-tratamiento en campos problema.",
      "• Almacenamiento en lugar fresco, seco y protegido de luz.",
    ]),
    caracteristicas: "Se comercializa en UY/AR/BR. Elección frecuente como alternativa a ivermectina en establecimientos con necesidad de rotación de moléculas.",
  }),
  buildFicha({
    nombre: "Draxxin",
    laboratorio: "Zoetis.",
    principio_activo: "Tulatromicina.",
    presentacion: "Solución inyectable 100 mg/mL.",
    via_administracion: "Subcutánea en bovinos.",
    especie: "Bovinos",
    tiempo_espera_carne: "18 DIAS (referencia ampliamente usada).",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS LECHERAS EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Macrólido triamilida para enfermedad respiratoria bovina (BRD).",
      "• Activo frente a Mannheimia haemolytica, Pasteurella multocida y Histophilus somni.",
      "• Dosis estándar: 2,5 mg/kg en dosis única SC.",
      "• También útil en queratoconjuntivitis y pododermatitis según etiqueta local.",
      "• Aplicar técnica SC correcta para minimizar reacciones locales.",
    ]),
    caracteristicas: "Muy difundido en UY/AR/BR para manejo metafiláctico y terapéutico de BRD. Favorece protocolos de dosis única en lotes con estrés por traslado o encierre.",
  }),
  buildFicha({
    nombre: "Ectocide",
    laboratorio: "Marca comercial de ectoparasiticidas en rumiantes.",
    principio_activo: "Combinaciones insecticidas (frecuente cipermetrina y/o organofosforados).",
    presentacion: "Concentrado emulsionable para baño o aspersión, y pour-on.",
    via_administracion: "Tópica.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "3 a 17 DIAS (segun ingrediente activo).",
    tiempo_espera_leche: "SEGUN FORMULACION; varias no recomendadas en ordeñe.",
    detalles_tecnicos: joinLines([
      "• Producto orientado a control de garrapata, piojos y moscas.",
      "• Requiere concentración exacta y cobertura homogénea del animal.",
      "• Repetición de baños según presión parasitaria y ciclo del vector.",
      "• Integrar con rotación de principios para prevenir resistencia.",
      "• Preparar solución fresca y desechar sobrantes de forma segura.",
    ]),
    caracteristicas: "Comercialización principal en UY y AR. Herramienta útil en planes de control externo en primavera-verano, combinada con manejo ambiental y monitoreo de eficacia.",
  }),
  buildFicha({
    nombre: "Elanco",
    laboratorio: "Elanco Animal Health, laboratorio líder en salud y productividad bovina.",
    principio_activo: "Líneas antiparasitarias, antimicrobianas, ionóforos y biológicos.",
    presentacion: "Inyectables, pour-on, orales, aditivos y vacunas según línea.",
    via_administracion: "SC, IM, oral y tópica según producto.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO DE LINEA.",
    tiempo_espera_leche: "SEGUN PRODUCTO; verificar etiqueta de cada país.",
    detalles_tecnicos: joinLines([
      "• Portafolio amplio para control parasitario, BRD y eficiencia productiva.",
      "• Incluye herramientas para tambo, cría e invernada intensiva.",
      "• Uso basado en diagnóstico, riesgo y objetivos de desempeño.",
      "• Promueve programas de uso responsable de antimicrobianos.",
      "• Conservación y manipulación conforme a ficha técnica específica.",
    ]),
    caracteristicas: "Presencia consolidada en UY/AR/BR. Adecuado para establecimientos que requieren cobertura integral desde prevención hasta tratamiento y acompañamiento técnico.",
  }),
  buildFicha({
    nombre: "Engemycin",
    laboratorio: "Zoetis en la mayoría de mercados.",
    principio_activo: "Oxitetraciclina de larga acción.",
    presentacion: "Inyectable LA 200 mg/mL.",
    via_administracion: "Intramuscular profunda o subcutánea según etiqueta.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "28 DIAS (valor de referencia frecuente).",
    tiempo_espera_leche: "96 HORAS aproximadas en formulaciones habilitadas.",
    detalles_tecnicos: joinLines([
      "• Antibiótico tetraciclínico de amplio espectro para infecciones bacterianas sensibles.",
      "• Indicado en neumonías, anaplasmosis, pododermatitis y metritis según diagnóstico.",
      "• Dosis orientativa: 20 mg/kg con intervalo según evolución clínica.",
      "• Limitar volumen por sitio para reducir reacción local.",
      "• Respetar indicaciones veterinarias y evitar uso indiscriminado.",
    ]),
    caracteristicas: "Muy utilizado en UY/AR/BR por versatilidad y disponibilidad. Recomendado en protocolos de campo cuando se necesita cobertura amplia y esquema práctico de aplicación.",
  }),
  buildFicha({
    nombre: "Eprinex",
    laboratorio: "Boehringer Ingelheim.",
    principio_activo: "Eprinomectina.",
    presentacion: "Pour-on 0,5% y formulaciones inyectables de larga acción en algunos mercados.",
    via_administracion: "Tópica dorsal (principal).",
    especie: "Bovinos",
    tiempo_espera_carne: "0 a 15 DIAS (segun presentación; pour-on usualmente 0).",
    tiempo_espera_leche: "0 DIAS para formulaciones registradas en vacas en ordeñe.",
    detalles_tecnicos: joinLines([
      "• Endectocida macrocíclico apto para manejo de rodeos lecheros en varias regiones.",
      "• Cubre nematodos GI/pulmonares y ectoparásitos sensibles.",
      "• Dosis típica pour-on: 1 mL/10 kg sobre línea dorsal seca.",
      "• Evitar aplicación en piel mojada o con barro para no afectar absorción.",
      "• Mantener envase cerrado y protegido de condiciones extremas.",
    ]),
    caracteristicas: "Comercialización en UY/AR/BR. Muy valorado en tambo por retiro de leche cero en registros específicos y facilidad de aplicación sin inyección.",
  }),
  buildFicha({
    nombre: "Excenel",
    laboratorio: "Zoetis/Pfizer histórico según mercado.",
    principio_activo: "Ceftiofur sódico.",
    presentacion: "Polvo estéril para reconstitución inyectable.",
    via_administracion: "Intramuscular o subcutánea según etiqueta.",
    especie: "Bovinos",
    tiempo_espera_carne: "4 DIAS (valor frecuente de etiqueta).",
    tiempo_espera_leche: "0 HORAS en varios registros.",
    detalles_tecnicos: joinLines([
      "• Cefalosporina de tercera generación para infecciones bacterianas sensibles.",
      "• Indicada en BRD, pododermatitis interdigital y metritis puerperal.",
      "• Dosis habitual: 1,1 a 2,2 mg/kg cada 24 h por 3 a 5 días.",
      "• Reconstituir y conservar según indicación para mantener estabilidad.",
      "• Uso prudente bajo criterio veterinario por su importancia crítica.",
    ]),
    caracteristicas: "Amplio uso en UY/AR/BR cuando se requiere antibiótico parenteral con retiro corto. Clave en casos clínicos confirmados y protocolos con seguimiento terapéutico.",
  }),
  buildFicha({
    nombre: "Excede",
    laboratorio: "Zoetis.",
    principio_activo: "Ceftiofur ácido cristalino libre.",
    presentacion: "Suspensión inyectable de liberación sostenida.",
    via_administracion: "Subcutánea en base de oreja según etiqueta bovina.",
    especie: "Bovinos",
    tiempo_espera_carne: "13 DIAS (referencia usual).",
    tiempo_espera_leche: "0 HORAS en vacas lecheras registradas.",
    detalles_tecnicos: joinLines([
      "• Cefalosporina de acción prolongada para BRD, pododermatitis y metritis.",
      "• Permite esquema de dosis única o dos dosis separadas por 72 h según indicación.",
      "• Sitio de aplicación específico para minimizar residuos en canal.",
      "• No mezclar con otros fármacos en la misma jeringa.",
      "• Seguir lineamientos de uso responsable de antimicrobianos críticos.",
    ]),
    caracteristicas: "Comercializado en UY/AR/BR para sistemas que requieren menor manipulación animal y cobertura extendida. Útil en lotes de alto riesgo respiratorio.",
  }),
  buildFicha({
    nombre: "Fasinex",
    laboratorio: "Novartis/Elanco según transición comercial.",
    principio_activo: "Triclabendazol.",
    presentacion: "Suspensión oral 10% para bovinos y ovinos.",
    via_administracion: "Oral.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "56 DIAS (referencia frecuente).",
    tiempo_espera_leche: "NO AUTORIZADO EN ORDEÑE en varias etiquetas.",
    detalles_tecnicos: joinLines([
      "• Fasciolicida específico con eficacia en formas inmaduras y adultas de Fasciola hepatica.",
      "• Recomendado en zonas húmedas con alta presión de fasciolosis.",
      "• Dosis orientativa bovinos: 12 mg/kg en administración única.",
      "• Integrar con manejo de potreros bajos y control de caracoles.",
      "• Evitar dosificaciones repetidas sin diagnóstico para reducir resistencia.",
    ]),
    caracteristicas: "Producto clásico en UY/AR/BR para fasciolosis. Fundamental en campos arroceros o bañados donde la duela hepática compromete condición corporal y fertilidad.",
  }),
  buildFicha({
    nombre: "Globion",
    laboratorio: "Globion, laboratorio veterinario con foco en producción pecuaria.",
    principio_activo: "Línea de biológicos y terapéuticos para bovinos.",
    presentacion: "Vacunas, inyectables y complementos sanitarios.",
    via_administracion: "SC/IM y otras vías según producto.",
    especie: "Bovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO; vacunas usualmente 0 DIAS.",
    tiempo_espera_leche: "SEGUN PRODUCTO.",
    detalles_tecnicos: joinLines([
      "• Portafolio orientado a prevención de enfermedades de impacto productivo.",
      "• Incluye líneas para inmunoprofilaxis y soporte terapéutico.",
      "• Programación recomendada por ciclo productivo y presión sanitaria local.",
      "• Requiere buenas prácticas de cadena de frío para biológicos.",
      "• Registrar lote y fecha para trazabilidad.",
    ]),
    caracteristicas: "Mayor presencia en AR. Alternativa de laboratorio regional para planes sanitarios de rodeo con énfasis preventivo y manejo estacional de riesgos.",
  }),
  buildFicha({
    nombre: "Hipra",
    laboratorio: "HIPRA, laboratorio líder en biológicos veterinarios.",
    principio_activo: "Vacunas y líneas inmunológicas para enfermedades respiratorias y reproductivas.",
    presentacion: "Vacunas inyectables y soluciones inmunomoduladoras.",
    via_administracion: "Subcutánea o intramuscular según biológico.",
    especie: "Bovinos",
    tiempo_espera_carne: "0 DIAS en biológicos habituales.",
    tiempo_espera_leche: "0 DIAS en biológicos habituales.",
    detalles_tecnicos: joinLines([
      "• Foco técnico en prevención de BRD, clostridiosis y salud reproductiva.",
      "• Programas de vacunación adaptables a cría, tambo y feedlot.",
      "• Requiere primovacunación y refuerzos para inmunidad sólida.",
      "• Mantener cadena de frío entre 2 y 8 C.",
      "• No mezclar vacunas salvo indicación expresa del fabricante.",
    ]),
    caracteristicas: "Presente en UY/AR/BR con fuerte soporte técnico. Marca preferida cuando el establecimiento prioriza prevención y reducción del uso terapéutico posterior.",
  }),
  buildFicha({
    nombre: "Hertape Calier",
    laboratorio: "Hertape Calier, laboratorio regional con soluciones para rumiantes.",
    principio_activo: "Líneas antiparasitarias, nutricionales y terapéuticas.",
    presentacion: "Inyectables, orales, pour-on y suplementos.",
    via_administracion: "SC, IM, oral y tópica.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO.",
    tiempo_espera_leche: "SEGUN PRODUCTO; revisar etiqueta vigente.",
    detalles_tecnicos: joinLines([
      "• Portfolio orientado a sistemas de carne y leche de la región.",
      "• Incluye soluciones para parásitos internos/externos y soporte metabólico.",
      "• La elección de molécula depende de diagnóstico y objetivo productivo.",
      "• Promover rotación antiparasitaria con monitoreo de eficacia.",
      "• Conservación acorde a especificación de cada presentación.",
    ]),
    caracteristicas: "Comercialización en BR y AR, con disponibilidad en circuitos regionales. Opción versátil para campos que requieren múltiples líneas sanitarias en un solo proveedor.",
  }),
  buildFicha({
    nombre: "Ivomec",
    laboratorio: "MSD/Merck Animal Health.",
    principio_activo: "Ivermectina 1%.",
    presentacion: "Inyectable SC 1%.",
    via_administracion: "Subcutánea.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "49 DIAS (SC 1% referencia).",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS LECHERAS EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Endectocida de referencia para control de nematodos y ectoparásitos sensibles.",
      "• Dosis estándar: 1 mL/50 kg (200 mcg/kg).",
      "• Útil en tratamientos estratégicos de otoño y primavera según zona.",
      "• Evaluar eficacia periódica con pruebas coproparasitológicas.",
      "• Conservar en lugar fresco y protegido de luz.",
    ]),
    caracteristicas: "Marca icónica en UY/AR/BR. Muy utilizada por robustez de evidencia y amplia adopción, con necesidad de manejo antiresistencia por uso histórico intensivo.",
  }),
  buildFicha({
    nombre: "Ivomec Gold",
    laboratorio: "MSD/Merck Animal Health.",
    principio_activo: "Ivermectina + Clorsulón.",
    presentacion: "Inyectable SC de acción extendida.",
    via_administracion: "Subcutánea.",
    especie: "Bovinos",
    tiempo_espera_carne: "122 DIAS (valor de referencia).",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS LECHERAS.",
    detalles_tecnicos: joinLines([
      "• Asociación endectocida + fasciolicida para control combinado.",
      "• Cubre nematodos sensibles y Fasciola hepatica adulta.",
      "• Dosis habitual: 1 mL/50 kg SC.",
      "• Indicado en planteos con coexistencia de helmintiasis y fasciolosis.",
      "• Respetar retiro prolongado por su persistencia tisular.",
    ]),
    caracteristicas: "Disponible en UY/AR/BR para campos con alto desafío parasitario mixto. Muy útil en otoño-invierno, con planificación comercial por retiro de carne extendido.",
  }),
  buildFicha({
    nombre: "Ivomec Pour-On",
    laboratorio: "MSD/Merck Animal Health.",
    principio_activo: "Ivermectina pour-on.",
    presentacion: "Solución tópica dorsal 0,5%.",
    via_administracion: "Tópica dorsal.",
    especie: "Bovinos",
    tiempo_espera_carne: "48 DIAS (referencia habitual).",
    tiempo_espera_leche: "NO AUTORIZADO EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Endectocida de aplicación externa para manejo sin aguja.",
      "• Controla nematodos y ectoparásitos sensibles según carga ambiental.",
      "• Dosis de referencia: 1 mL/10 kg sobre línea dorsal.",
      "• Aplicar sobre piel seca y limpia para optimizar absorción.",
      "• Evitar lluvia inmediata post-aplicación cuando lo indique etiqueta.",
    ]),
    caracteristicas: "Comercializado en UY/AR/BR. Opción práctica para grandes lotes y reducción de estrés de manejo, especialmente en sistemas extensivos.",
  }),
  buildFicha({
    nombre: "Ivosan",
    laboratorio: "Marca antiparasitaria de uso regional.",
    principio_activo: "Ivermectina.",
    presentacion: "Inyectable 1% y variantes comerciales.",
    via_administracion: "Subcutánea.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "35 a 49 DIAS.",
    tiempo_espera_leche: "NO USAR EN VACAS EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Endectocida para helmintos GI/pulmonares y ectoparásitos susceptibles.",
      "• Dosis orientativa: 200 mcg/kg.",
      "• Adecuado para tratamientos estratégicos por categoría.",
      "• Ajustar aplicación por peso real para sostener eficacia.",
      "• Conservación en sitio fresco y protegido de la luz.",
    ]),
    caracteristicas: "Marca presente en UY/AR/BR, usual en esquemas sanitarios de cría e invernada. Conveniente por disponibilidad comercial y costo operativo.",
  }),
  buildFicha({
    nombre: "Ivercass",
    laboratorio: "Marca comercial de lactona macrocíclica.",
    principio_activo: "Ivermectina.",
    presentacion: "Inyectable SC y/o pour-on según versión.",
    via_administracion: "Subcutánea o tópica.",
    especie: "Bovinos",
    tiempo_espera_carne: "35 a 49 DIAS.",
    tiempo_espera_leche: "NO AUTORIZADO EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Control de nematodos gastrointestinales y pulmonares sensibles.",
      "• Coadyuva en manejo de piojos y ácaros en campañas estacionales.",
      "• Dosis estándar para 1%: 1 mL/50 kg.",
      "• Programar tratamiento junto a manejo de pasturas y carga animal.",
      "• Verificar integridad del envase antes del uso.",
    ]),
    caracteristicas: "Comercializada en UY/AR/BR. Se usa en planes antiparasitarios de rutina, especialmente cuando se busca alternativa de marca en ivermectinas convencionales.",
  }),
  buildFicha({
    nombre: "Ivermet",
    laboratorio: "Marca regional de endectocidas.",
    principio_activo: "Ivermectina.",
    presentacion: "Inyectable 1% y formulaciones relacionadas.",
    via_administracion: "Subcutánea.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "35 a 49 DIAS.",
    tiempo_espera_leche: "NO AUTORIZADO EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Antiparasitario sistémico con espectro sobre endo y ectoparásitos.",
      "• Dosis orientativa 1%: 200 mcg/kg.",
      "• Útil en tratamientos estratégicos de recría y pre-servicio.",
      "• Considerar rotación con otras familias por resistencia.",
      "• Mantener almacenamiento controlado y sin exposición UV.",
    ]),
    caracteristicas: "Presente en UY/AR/BR. Producto de uso práctico para control sanitario general, con necesidad de monitoreo de respuesta clínica y coproparasitológica.",
  }),
  buildFicha({
    nombre: "J.A. Baker",
    laboratorio: "J.A. Baker, marca asociada a insumos y compuestos de uso veterinario/técnico.",
    principio_activo: "Líneas antisépticas, desinfectantes y formulaciones de soporte.",
    presentacion: "Soluciones líquidas, concentrados y preparados técnicos.",
    via_administracion: "Tópica y de uso instrumental/ambiental según producto.",
    especie: "Bovinos",
    tiempo_espera_carne: "NO APLICA en productos de higiene y desinfección.",
    tiempo_espera_leche: "NO APLICA.",
    detalles_tecnicos: joinLines([
      "• Productos orientados a bioseguridad, antisepsia y manejo higiénico.",
      "• Uso frecuente en preparación de instalaciones y material de trabajo.",
      "• Debe respetarse dilución correcta para eficacia y seguridad.",
      "• Evitar contacto directo con mucosas si no está indicado.",
      "• Conservar en envases originales cerrados y rotulados.",
    ]),
    caracteristicas: "Disponibilidad en UY/AR/BR para soporte de buenas prácticas sanitarias. Aporta valor en prevención indirecta al reducir carga ambiental de patógenos.",
  }),
  buildFicha({
    nombre: "Konig",
    laboratorio: "König, laboratorio veterinario con fuerte presencia en Argentina.",
    principio_activo: "Líneas antiparasitarias, antibióticas y antiinflamatorias.",
    presentacion: "Inyectables, orales, tópicos y suplementos.",
    via_administracion: "SC, IM, oral y tópica según producto.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO.",
    tiempo_espera_leche: "SEGUN PRODUCTO; validar etiqueta.",
    detalles_tecnicos: joinLines([
      "• Portfolio amplio para manejo sanitario integral de rodeos.",
      "• Incluye formulaciones para control parasitario y patología infecciosa.",
      "• La elección terapéutica debe basarse en diagnóstico de campo.",
      "• Recomendable registro de tratamientos para trazabilidad y auditoría.",
      "• Mantener productos en depósitos acondicionados.",
    ]),
    caracteristicas: "Marca de alta presencia en AR. Utilizada por su oferta amplia y continuidad comercial en veterinarias rurales y distribuidores técnicos.",
  }),
  buildFicha({
    nombre: "Labinco",
    laboratorio: "Labinco, laboratorio veterinario con participación en mercado uruguayo.",
    principio_activo: "Líneas antiparasitarias, antibióticos y soporte metabólico.",
    presentacion: "Inyectables, orales y tópicos.",
    via_administracion: "SC, IM, oral y tópica según formulación.",
    especie: "Bovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO.",
    tiempo_espera_leche: "SEGUN PRODUCTO.",
    detalles_tecnicos: joinLines([
      "• Soluciones para patologías frecuentes de cría y engorde.",
      "• Portafolio con enfoque en practicidad de uso en campo.",
      "• Definir dosis estricta por peso y diagnóstico.",
      "• Integrar con calendario sanitario anual del establecimiento.",
      "• Conservar conforme a recomendaciones del fabricante.",
    ]),
    caracteristicas: "Presencia principal en UY. Opción local para campos que priorizan abastecimiento cercano y variedad de productos para manejo diario.",
  }),
  buildFicha({
    nombre: "Lafox",
    laboratorio: "Marca comercial de antiparasitarios para rumiantes.",
    principio_activo: "Rafoxanida y/o combinaciones antihelmínticas según versión.",
    presentacion: "Solución oral y formulaciones inyectables en algunos mercados.",
    via_administracion: "Oral (principal) y/o inyectable.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "28 a 60 DIAS (segun formulacion).",
    tiempo_espera_leche: "NO AUTORIZADO EN ORDEÑE en varias presentaciones.",
    detalles_tecnicos: joinLines([
      "• Fasciolicida/antihelmíntico orientado a control de duelas y nematodos específicos.",
      "• Útil en esquemas de otoño-invierno en zonas de riesgo de fasciola.",
      "• Dosis varía por concentración y objetivo parasitario.",
      "• Combinar con manejo de potreros encharcados para mejor control.",
      "• Agitar bien antes de dosificar por vía oral.",
    ]),
    caracteristicas: "Comercialización en UY/AR/BR. Empleado en planes dirigidos a fasciolosis y parasitosis mixtas cuando se busca complementar lactonas macrocíclicas.",
  }),
  buildFicha({
    nombre: "Longrange",
    laboratorio: "Boehringer Ingelheim.",
    principio_activo: "Eprinomectina de larga acción.",
    presentacion: "Inyectable SC de liberación prolongada.",
    via_administracion: "Subcutánea.",
    especie: "Bovinos",
    tiempo_espera_carne: "48 a 60 DIAS (segun etiqueta local).",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Endectocida con persistencia extendida para control prolongado de nematodos.",
      "• Dosis orientativa: 1 mL/50 kg en aplicación única.",
      "• Indicado para cubrir periodos críticos de infestación en recría y engorde.",
      "• Evitar retratamientos innecesarios por su larga residualidad.",
      "• Registrar fecha para respetar retiro previo a faena.",
    ]),
    caracteristicas: "Muy usado en UY/AR/BR cuando se busca ventana larga de protección y menor frecuencia de encierres. Requiere planificación por retiro y costo por dosis.",
  }),
  buildFicha({
    nombre: "Maximec",
    laboratorio: "Marca comercial de antiparasitario endectocida.",
    principio_activo: "Ivermectina.",
    presentacion: "Inyectable 1% y variantes comerciales.",
    via_administracion: "Subcutánea.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "35 a 49 DIAS.",
    tiempo_espera_leche: "NO USAR EN VACAS LECHERAS EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Lactona macrocíclica para control de nematodos y ectoparásitos sensibles.",
      "• Dosis estándar: 200 mcg/kg.",
      "• Empleo estratégico en momentos de mayor desafío parasitario.",
      "• Ajustar manejo para evitar selección de resistencia.",
      "• Mantener producto en condiciones de almacenamiento seguras.",
    ]),
    caracteristicas: "Disponible en UY/AR/BR. Producto de uso frecuente por su simplicidad operativa y cobertura de parásitos clave en bovinos de carne.",
  }),
  buildFicha({
    nombre: "Merck Animal Health",
    laboratorio: "Merck Animal Health, laboratorio líder global en medicina veterinaria.",
    principio_activo: "Líneas antiparasitarias, antimicrobianas, antiinflamatorias y vacunas.",
    presentacion: "Inyectables, orales, pour-on y biológicos.",
    via_administracion: "SC, IM, oral y tópica según producto.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO.",
    tiempo_espera_leche: "SEGUN PRODUCTO.",
    detalles_tecnicos: joinLines([
      "• Portfolio robusto para control de parasitosis, BRD y dolor/inflamación.",
      "• Incluye marcas de referencia para sistemas de carne y leche.",
      "• Protocolos deben adaptarse al riesgo sanitario y fase productiva.",
      "• Uso responsable de antimicrobianos con base diagnóstica.",
      "• Conservación diferenciada según categoría farmacéutica.",
    ]),
    caracteristicas: "Presencia fuerte en UY/AR/BR. Proveedor estratégico para campos que demandan soluciones integrales con alta estandarización técnica.",
  }),
  buildFicha({
    nombre: "Metacam",
    laboratorio: "Boehringer Ingelheim.",
    principio_activo: "Meloxicam.",
    presentacion: "Inyectable 20 mg/mL y suspensión oral en algunas líneas.",
    via_administracion: "Subcutánea, intravenosa y oral según registro.",
    especie: "Bovinos",
    tiempo_espera_carne: "15 DIAS aproximados (inyectable bovino).",
    tiempo_espera_leche: "5 DIAS aproximados en formulaciones para tambo.",
    detalles_tecnicos: joinLines([
      "• AINE de alta selectividad para manejo de dolor, inflamación y fiebre.",
      "• Indicado como coadyuvante en mastitis, metritis, neumonía y procedimientos.",
      "• Dosis frecuente: 0,5 mg/kg en dosis única o corta repetición.",
      "• Mejorar confort y recuperación posprocedimiento en terneros y vacas.",
      "• Evitar combinación con otros AINE sin indicación profesional.",
    ]),
    caracteristicas: "Comercializado en UY/AR/BR y muy valorado por perfil antiinflamatorio. Herramienta clave en bienestar animal y protocolos de medicina del dolor en campo.",
  }),
  buildFicha({
    nombre: "Micotil",
    laboratorio: "Elanco (históricamente Lilly).",
    principio_activo: "Tilmicosina.",
    presentacion: "Inyectable 300 mg/mL.",
    via_administracion: "Subcutánea en bovinos.",
    especie: "Bovinos",
    tiempo_espera_carne: "28 DIAS (referencia habitual).",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS LECHERAS EN PRODUCCION.",
    detalles_tecnicos: joinLines([
      "• Macrólido para tratamiento de enfermedad respiratoria bovina.",
      "• Activo frente a Mannheimia, Pasteurella e Histophilus sensibles.",
      "• Dosis orientativa: 10 mg/kg en dosis única SC.",
      "• Producto de manejo restringido por seguridad ocupacional del operador.",
      "• Usar equipo de protección y evitar autoinyección accidental.",
    ]),
    caracteristicas: "Disponible en UY/AR/BR en esquemas respiratorios de feedlot y recría. Requiere capacitación del personal por riesgos de manipulación humana.",
  }),
  buildFicha({
    nombre: "Morvia",
    laboratorio: "Morvia, laboratorio veterinario de mercado uruguayo.",
    principio_activo: "Líneas antiparasitarias, antimicrobianas y complementos.",
    presentacion: "Inyectables, orales y tópicos.",
    via_administracion: "SC, IM, oral y tópica.",
    especie: "Bovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO.",
    tiempo_espera_leche: "SEGUN PRODUCTO.",
    detalles_tecnicos: joinLines([
      "• Soluciones de uso frecuente en establecimientos de cría e invernada.",
      "• Incluye productos para control parasitario y soporte terapéutico general.",
      "• Ajustar protocolos a diagnóstico y antecedentes sanitarios del predio.",
      "• Registrar tratamientos para control de retiros y auditoría interna.",
      "• Mantener condiciones adecuadas de almacenamiento.",
    ]),
    caracteristicas: "Presencia destacada en UY. Se utiliza por cercanía comercial y respuesta rápida de reposición en veterinarias rurales.",
  }),
  buildFicha({
    nombre: "MSD Salud Animal",
    laboratorio: "MSD Salud Animal, laboratorio líder en bovinos en la región.",
    principio_activo: "Líneas antiparasitarias, antibióticas, antiinflamatorias y vacunas.",
    presentacion: "Inyectables, pour-on, orales y biológicos.",
    via_administracion: "SC, IM, oral y tópica según producto.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO DE LINEA.",
    tiempo_espera_leche: "SEGUN PRODUCTO; revisar rótulo local.",
    detalles_tecnicos: joinLines([
      "• Portafolio de referencia con marcas históricas en antiparasitarios y BRD.",
      "• Cobertura para sistemas de cría, tambo y engorde intensivo.",
      "• Protocolos recomendados por categoría, riesgo epidemiológico y época.",
      "• Fuerte enfoque en farmacovigilancia y uso responsable.",
      "• Requiere cumplimiento estricto de conservación por línea.",
    ]),
    caracteristicas: "Amplia cobertura en UY/AR/BR. Opción prioritaria en campos que buscan respaldo técnico global y disponibilidad sostenida de productos clave.",
  }),
  buildFicha({
    nombre: "Naxcel",
    laboratorio: "Zoetis/Pfizer histórico.",
    principio_activo: "Ceftiofur sódico.",
    presentacion: "Polvo estéril reconstituible para inyección.",
    via_administracion: "IM o SC según etiqueta.",
    especie: "Bovinos",
    tiempo_espera_carne: "4 DIAS.",
    tiempo_espera_leche: "0 HORAS en muchos registros bovinos.",
    detalles_tecnicos: joinLines([
      "• Cefalosporina de tercera generación para infecciones bacterianas sensibles.",
      "• Indicada en BRD y otras patologías bacterianas de relevancia productiva.",
      "• Dosis habitual: 1,1 a 2,2 mg/kg cada 24 h.",
      "• Cumplir reconstitución y vida útil de solución preparada.",
      "• Uso racional indispensable por criticidad terapéutica.",
    ]),
    caracteristicas: "Comercializado en UY/AR/BR. Valorado por retiro corto y respuesta clínica en cuadros agudos, dentro de protocolos con criterio microbiológico.",
  }),
  buildFicha({
    nombre: "Ouro Fino Saúde Animal",
    laboratorio: "Ourofino Saúde Animal, laboratorio líder brasileño con expansión regional.",
    principio_activo: "Líneas antiparasitarias, antimicrobianas, vacunas y reproducción.",
    presentacion: "Inyectables, pour-on, orales y biológicos.",
    via_administracion: "SC, IM, oral y tópica según línea.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO.",
    tiempo_espera_leche: "SEGUN PRODUCTO; confirmar registro local.",
    detalles_tecnicos: joinLines([
      "• Portafolio robusto para carne y leche con foco en productividad tropical.",
      "• Incluye antiparasitarios de amplio uso y terapias para BRD y reproducción.",
      "• Ajustar planes sanitarios según presión parasitaria y clima.",
      "• Integrar tratamientos con manejo nutricional y bienestar.",
      "• Conservar bajo condiciones especificadas por presentación.",
    ]),
    caracteristicas: "Fuerte presencia en BR con comercialización en UY/AR. Elegido por amplitud de línea y adaptación a sistemas extensivos e intensivos regionales.",
  }),
  buildFicha({
    nombre: "Panacur",
    laboratorio: "MSD/Intervet en varios mercados.",
    principio_activo: "Fenbendazol.",
    presentacion: "Suspensión oral, pasta y bolos.",
    via_administracion: "Oral.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "8 a 14 DIAS (segun formulacion).",
    tiempo_espera_leche: "0 a 72 HORAS segun registro local.",
    detalles_tecnicos: joinLines([
      "• Benzimidazol de amplio espectro para nematodos GI y pulmonares.",
      "• También activo sobre algunos cestodos y fases larvarias según dosis.",
      "• Dosis bovinos frecuente: 5 mg/kg por vía oral.",
      "• Excelente opción para rotación antihelmíntica en programas integrados.",
      "• Agitar bien y dosificar con equipo calibrado.",
    ]),
    caracteristicas: "Comercializado en UY/AR/BR. Muy usado en terneros y ovinos por seguridad y versatilidad de formulaciones orales.",
  }),
  buildFicha({
    nombre: "Panacur 25",
    laboratorio: "MSD/Intervet.",
    principio_activo: "Fenbendazol 2,5%.",
    presentacion: "Suspensión oral 2,5% para rumiantes jóvenes y adultos.",
    via_administracion: "Oral.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "10 a 14 DIAS.",
    tiempo_espera_leche: "48 a 72 HORAS segun etiqueta.",
    detalles_tecnicos: joinLines([
      "• Formulación oral de fenbendazol para control de helmintos sensibles.",
      "• Dosis típica: 5 mg/kg, ajustada a concentración 2,5%.",
      "• Útil en recría y categorías de manejo frecuente en manga.",
      "• Integrar con monitoreo HPG para ajustar intervalos de tratamiento.",
      "• Conservar en ambiente seco y templado.",
    ]),
    caracteristicas: "Disponible en UY/AR/BR. Alternativa práctica cuando se requiere una concentración intermedia para dosificación precisa en lotes heterogéneos.",
  }),
  buildFicha({
    nombre: "Panzer",
    laboratorio: "Marca comercial de antiparasitarios en ganadería.",
    principio_activo: "Ivermectina (principalmente 1%).",
    presentacion: "Inyectable SC y/o pour-on según mercado.",
    via_administracion: "Subcutánea o tópica.",
    especie: "Bovinos",
    tiempo_espera_carne: "35 a 49 DIAS.",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Endectocida para helmintiasis gastrointestinal y pulmonar.",
      "• Contribuye al control de piojos y ácaros sensibles.",
      "• Dosis referencial en 1%: 1 mL/50 kg.",
      "• Debe emplearse en planes estratégicos por categoría y estación.",
      "• Conservar en envase original, evitando contaminación.",
    ]),
    caracteristicas: "Comercialización en UY/AR/BR. Opción de campo para programas básicos de control parasitario con logística simple de aplicación.",
  }),
  buildFicha({
    nombre: "Provet",
    laboratorio: "Provet, laboratorio veterinario con enfoque local en Uruguay.",
    principio_activo: "Líneas antiparasitarias, antibióticas y de soporte.",
    presentacion: "Inyectables, orales y productos tópicos.",
    via_administracion: "SC, IM, oral y tópica.",
    especie: "Bovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO.",
    tiempo_espera_leche: "SEGUN PRODUCTO.",
    detalles_tecnicos: joinLines([
      "• Portafolio para manejo sanitario cotidiano de rodeos de carne y leche.",
      "• Incluye herramientas para control parasitario y cuadros infecciosos comunes.",
      "• Recomendable uso bajo plan sanitario definido por veterinario actuante.",
      "• Priorizar técnicas correctas de aplicación y bioseguridad.",
      "• Mantener almacenamiento en rangos térmicos recomendados.",
    ]),
    caracteristicas: "Presencia principal en UY. Elegido por cercanía operativa y disponibilidad en distribuidores rurales locales.",
  }),
  buildFicha({
    nombre: "Richet",
    laboratorio: "Richet, laboratorio veterinario argentino.",
    principio_activo: "Líneas antiparasitarias, antibióticas y antiinflamatorias.",
    presentacion: "Inyectables, orales y tópicos.",
    via_administracion: "SC, IM, oral y tópica según línea.",
    especie: "Bovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO.",
    tiempo_espera_leche: "SEGUN PRODUCTO.",
    detalles_tecnicos: joinLines([
      "• Soluciones para patologías prevalentes en sistemas de cría e invernada.",
      "• Portafolio orientado a practicidad y cobertura terapéutica general.",
      "• Aplicar bajo diagnóstico clínico y criterio epidemiológico del establecimiento.",
      "• Registrar tratamientos para control de retiros y auditorías.",
      "• Conservar en condiciones higiénicas y de temperatura estable.",
    ]),
    caracteristicas: "Comercialización principal en AR. Marca utilizada por continuidad de abastecimiento y variedad de opciones terapéuticas.",
  }),
  buildFicha({
    nombre: "Rycoben",
    laboratorio: "Marca antiparasitaria de uso regional.",
    principio_activo: "Albendazol.",
    presentacion: "Suspensión oral 10%.",
    via_administracion: "Oral.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "14 a 28 DIAS.",
    tiempo_espera_leche: "48 a 96 HORAS en presentaciones autorizadas.",
    detalles_tecnicos: joinLines([
      "• Benzimidazol de amplio espectro frente a nematodos GI y pulmonares.",
      "• Actividad sobre cestodos y fasciola adulta con dosis ajustada.",
      "• Dosis orientativa: 7,5 mg/kg en bovinos.",
      "• Uso estratégico en otoño y al ingreso a pasturas de riesgo.",
      "• Agitar antes de usar y dosificar con pistola calibrada.",
    ]),
    caracteristicas: "Amplia disponibilidad en UY/AR/BR. Producto clásico de desparasitación oral, especialmente útil en programas mixtos bovino-ovino.",
  }),
  buildFicha({
    nombre: "Supasin",
    laboratorio: "Marca terapéutica de uso ganadero en la región.",
    principio_activo: "Sulfamidas potenciadas y/o combinaciones antimicrobianas según versión.",
    presentacion: "Inyectable y oral según formulación comercial.",
    via_administracion: "IM, IV lenta u oral según etiqueta.",
    especie: "Bovinos",
    tiempo_espera_carne: "10 a 28 DIAS (segun formulacion).",
    tiempo_espera_leche: "3 a 5 DIAS en formulaciones aptas para tambo.",
    detalles_tecnicos: joinLines([
      "• Antimicrobiano de amplio uso en infecciones bacterianas sensibles.",
      "• Frecuente en cuadros digestivos, respiratorios y sistémicos de campo.",
      "• Dosis y duración dependen de concentración y gravedad clínica.",
      "• Asegurar hidratación adecuada del animal tratado.",
      "• Evitar empleo empírico prolongado sin reevaluación clínica.",
    ]),
    caracteristicas: "Comercializado en UY/AR/BR. Útil como alternativa terapéutica en patologías bacterianas comunes, siempre con criterio veterinario y control de retiros.",
  }),
  buildFicha({
    nombre: "Supracid",
    laboratorio: "Marca de ectoparasiticidas para rumiantes.",
    principio_activo: "Combinaciones insecticidas (piretroides y/o organofosforados) según presentación.",
    presentacion: "Concentrado para baño/aspersión y soluciones tópicas.",
    via_administracion: "Tópica.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "3 a 17 DIAS según principio activo.",
    tiempo_espera_leche: "SEGUN FORMULACION; puede no autorizarse en ordeñe.",
    detalles_tecnicos: joinLines([
      "• Indicado para control de mosca, piojos y garrapata en programas integrados.",
      "• Preparar dilución exacta y garantizar mojado completo del animal.",
      "• Repetir aplicaciones según ciclo del parásito y presión ambiental.",
      "• Rotar familia química para reducir resistencia.",
      "• Manejar remanentes y envases con criterio ambiental.",
    ]),
    caracteristicas: "Disponibilidad en UY/AR/BR. Herramienta práctica para campañas de ectoparásitos en primavera-verano, complementada con manejo de potreros e instalaciones.",
  }),
  buildFicha({
    nombre: "Tasignol",
    laboratorio: "Marca comercial de antiparasitarios de amplio uso.",
    principio_activo: "Combinaciones antihelmínticas (frecuente levamisol + benzimidazol según versión).",
    presentacion: "Oral e inyectable según formulación.",
    via_administracion: "Oral o subcutánea.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "14 a 28 DIAS.",
    tiempo_espera_leche: "48 a 96 HORAS o no autorizado según versión.",
    detalles_tecnicos: joinLines([
      "• Producto orientado a ampliar espectro frente a nematodos digestivos.",
      "• Útil cuando se requiere combinar mecanismos de acción antihelmíntica.",
      "• Dosificar por peso real para asegurar eficacia clínica.",
      "• Recomendable monitorizar respuesta para ajustar estrategia anual.",
      "• Conservar en envase cerrado, sin exposición térmica extrema.",
    ]),
    caracteristicas: "Comercialización regional en UY/AR/BR. Usado en esquemas de rotación y en rodeos con historial de respuesta parcial a monodrogas.",
  }),
  buildFicha({
    nombre: "Taurador",
    laboratorio: "Marca comercial de sanidad bovina en Cono Sur.",
    principio_activo: "Líneas antiparasitarias inyectables y tópicas según mercado.",
    presentacion: "Inyectable y pour-on.",
    via_administracion: "SC o tópica según presentación.",
    especie: "Bovinos",
    tiempo_espera_carne: "35 a 60 DIAS (segun formulacion).",
    tiempo_espera_leche: "NO USAR EN ORDEÑE salvo indicación específica.",
    detalles_tecnicos: joinLines([
      "• Formulaciones orientadas a control de endo y ectoparásitos.",
      "• Esquema de uso dependiente del desafío parasitario local.",
      "• Dosis definida por concentración y peso del animal.",
      "• Integrar con prácticas de manejo y calendario sanitario.",
      "• Verificar etiqueta para retiros y restricciones de uso.",
    ]),
    caracteristicas: "Presencia en UY/AR/BR. Opción de campo para planificación sanitaria de rodeos de carne con enfoque operativo simple.",
  }),
  buildFicha({
    nombre: "Tecnopec",
    laboratorio: "Tecnopec, laboratorio veterinario con cobertura regional.",
    principio_activo: "Líneas antiparasitarias, antibióticas y metabólicas.",
    presentacion: "Inyectables, orales y tópicos.",
    via_administracion: "SC, IM, oral y tópica.",
    especie: "Bovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO.",
    tiempo_espera_leche: "SEGUN PRODUCTO.",
    detalles_tecnicos: joinLines([
      "• Portafolio aplicado a salud de rodeos de carne y leche.",
      "• Incluye opciones terapéuticas para patologías frecuentes de campo.",
      "• Definir protocolos según diagnóstico y metas productivas.",
      "• Registrar cada aplicación para trazabilidad y control de retiro.",
      "• Mantener condiciones adecuadas de almacenaje.",
    ]),
    caracteristicas: "Comercializado en AR y UY. Marca utilizada cuando se prioriza proveedor regional con cartera amplia para manejo sanitario rutinario.",
  }),
  buildFicha({
    nombre: "Terramicina LA",
    laboratorio: "Zoetis/Pfizer histórico.",
    principio_activo: "Oxitetraciclina de larga acción.",
    presentacion: "Inyectable LA 200 mg/mL.",
    via_administracion: "IM profunda o SC según etiqueta.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "28 a 35 DIAS.",
    tiempo_espera_leche: "96 HORAS aproximadas en formulaciones autorizadas.",
    detalles_tecnicos: joinLines([
      "• Antibiótico de amplio espectro para infecciones respiratorias y sistémicas.",
      "• Indicado en anaplasmosis, queratoconjuntivitis y podales según diagnóstico.",
      "• Dosis habitual: 20 mg/kg con repetición según evolución.",
      "• No exceder volumen recomendado por sitio de aplicación.",
      "• Uso prudente para minimizar selección de resistencia.",
    ]),
    caracteristicas: "Muy difundido en UY/AR/BR por versatilidad clínica. Producto clásico para terapéutica de campo cuando se requiere cobertura amplia y buena disponibilidad.",
  }),
  buildFicha({
    nombre: "Tulamax",
    laboratorio: "Marca comercial de macrólido inyectable en bovinos.",
    principio_activo: "Tulatromicina.",
    presentacion: "Inyectable 100 mg/mL.",
    via_administracion: "Subcutánea.",
    especie: "Bovinos",
    tiempo_espera_carne: "18 a 22 DIAS (segun registro local).",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Macrólido de acción prolongada para enfermedad respiratoria bovina.",
      "• Dosis estándar: 2,5 mg/kg en dosis única.",
      "• Activo frente a agentes bacterianos clave del complejo respiratorio.",
      "• Útil en metafilaxia de lotes con alto estrés de ingreso.",
      "• Aplicar con técnica SC correcta y aguja adecuada.",
    ]),
    caracteristicas: "Comercialización en UY/AR/BR. Alternativa terapéutica de dosis única para BRD, práctica en manejo de lotes numerosos.",
  }),
  buildFicha({
    nombre: "Valbazen",
    laboratorio: "Zoetis/Pfizer histórico.",
    principio_activo: "Albendazol.",
    presentacion: "Suspensión oral 11,36%.",
    via_administracion: "Oral.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "27 DIAS (valor de referencia frecuente).",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS LECHERAS EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Benzimidazol con amplio espectro antihelmíntico.",
      "• Cubre nematodos GI/pulmonares y actividad sobre cestodos.",
      "• En dosis específicas aporta acción contra fasciola adulta.",
      "• Dosis orientativa bovina: 7,5 mg/kg por vía oral.",
      "• Evitar uso en primer tercio de gestación según etiqueta.",
    ]),
    caracteristicas: "Producto muy conocido en UY/AR/BR. Relevante para planes de desparasitación oral con foco en helmintiasis mixtas y categorías de recría.",
  }),
  buildFicha({
    nombre: "Vallée",
    laboratorio: "Vallée, laboratorio brasileño de amplia trayectoria en rumiantes.",
    principio_activo: "Líneas de vacunas, antiparasitarios y terapias inyectables.",
    presentacion: "Biológicos, inyectables y formulaciones antiparasitarias.",
    via_administracion: "SC, IM y otras vías según producto.",
    especie: "Bovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO.",
    tiempo_espera_leche: "SEGUN PRODUCTO.",
    detalles_tecnicos: joinLines([
      "• Fuerte presencia en prevención y terapéutica de bovinos de carne.",
      "• Incluye líneas para clostridiosis, respiratorio y control de parásitos.",
      "• El protocolo óptimo depende del sistema productivo y estación.",
      "• Manejo correcto de cadena de frío en vacunas es crítico.",
      "• Registrar lote de biológicos para trazabilidad sanitaria.",
    ]),
    caracteristicas: "Comercialización principal en BR y AR. Laboratorio elegido en sistemas que combinan prevención intensiva y terapéutica de campo.",
  }),
  buildFicha({
    nombre: "Verben",
    laboratorio: "Marca antiparasitaria de uso bovino regional.",
    principio_activo: "Ivermectina y/o combinaciones según línea.",
    presentacion: "Inyectable SC y tópicos.",
    via_administracion: "Subcutánea y tópica.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "35 a 49 DIAS.",
    tiempo_espera_leche: "NO AUTORIZADO EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Endectocida orientado a control de helmintos y ectoparásitos sensibles.",
      "• Dosis estándar según concentración declarada en etiqueta.",
      "• Aplicación estratégica en momentos de máxima exposición.",
      "• Recomendable alternar con otras familias antihelmínticas.",
      "• Verificar integridad del envase y fecha de vencimiento.",
    ]),
    caracteristicas: "Disponible en UY/AR/BR. Opción práctica para planes sanitarios de rutina con enfoque en control parasitario integral.",
  }),
  buildFicha({
    nombre: "Vermitan",
    laboratorio: "Marca comercial de antihelmínticos para rumiantes.",
    principio_activo: "Levamisol y/o asociaciones según presentación.",
    presentacion: "Inyectable y oral.",
    via_administracion: "Subcutánea u oral.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "7 a 14 DIAS (segun formulacion).",
    tiempo_espera_leche: "24 a 72 HORAS segun etiqueta.",
    detalles_tecnicos: joinLines([
      "• Antihelmíntico con acción sobre nematodos gastrointestinales y pulmonares.",
      "• En algunas formulaciones se combina para ampliar espectro.",
      "• Dosis precisa por kg es clave por menor margen terapéutico.",
      "• Útil en rotación para reducir presión de resistencia.",
      "• No administrar a animales debilitados sin evaluación previa.",
    ]),
    caracteristicas: "Comercialización en UY/AR/BR. Se utiliza como alternativa a lactonas y benzimidazoles dentro de esquemas de rotación estratégica.",
  }),
  buildFicha({
    nombre: "Vetanco",
    laboratorio: "Vetanco, laboratorio regional con soluciones para producción animal.",
    principio_activo: "Líneas antimicrobianas, antiparasitarias y aditivos.",
    presentacion: "Inyectables, orales, premezclas y biológicos.",
    via_administracion: "IM, SC, oral y tópica según línea.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO.",
    tiempo_espera_leche: "SEGUN PRODUCTO.",
    detalles_tecnicos: joinLines([
      "• Portafolio integral para sanidad, prevención y soporte productivo.",
      "• Cubre patologías respiratorias, digestivas y parasitarias relevantes.",
      "• Implementación recomendada bajo plan sanitario anual.",
      "• Favorece enfoque de medicina preventiva y trazabilidad.",
      "• Conservación específica según forma farmacéutica.",
    ]),
    caracteristicas: "Presencia en AR/UY/BR con buen soporte comercial. Adecuado para establecimientos que buscan proveedor regional con soluciones múltiples para campo.",
  }),
  buildFicha({
    nombre: "Vetoquinol",
    laboratorio: "Vetoquinol, laboratorio líder internacional en salud animal.",
    principio_activo: "Líneas antiinflamatorias, antimicrobianas y antiparasitarias.",
    presentacion: "Inyectables, orales y tópicos.",
    via_administracion: "IM, SC, oral y tópica según presentación.",
    especie: "Bovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO.",
    tiempo_espera_leche: "SEGUN PRODUCTO; revisar marbete local.",
    detalles_tecnicos: joinLines([
      "• Portafolio de calidad farmacéutica para medicina de producción.",
      "• Incluye terapias para dolor, infección y control de parásitos.",
      "• Selección terapéutica basada en diagnóstico y objetivo productivo.",
      "• Se recomienda seguimiento clínico y registros de tratamiento.",
      "• Condiciones de almacenamiento según ficha técnica.",
    ]),
    caracteristicas: "Comercialización en UY/AR/BR. Laboratorio elegido por respaldo técnico internacional y consistencia de formulaciones para uso profesional.",
  }),
  buildFicha({
    nombre: "Virbac",
    laboratorio: "Virbac, laboratorio líder global con fuerte presencia en rumiantes.",
    principio_activo: "Líneas antiparasitarias, vacunas y terapéutica general.",
    presentacion: "Inyectables, orales, pour-on y biológicos.",
    via_administracion: "SC, IM, oral y tópica.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO.",
    tiempo_espera_leche: "SEGUN PRODUCTO.",
    detalles_tecnicos: joinLines([
      "• Portfolio orientado a prevención y tratamiento en producción bovina.",
      "• Ofrece moléculas para control interno/externo y cuadros infecciosos.",
      "• Requiere integración con diagnóstico de establecimiento.",
      "• Fomenta manejo responsable y protocolos por categoría.",
      "• Mantener cadena de conservación indicada para cada línea.",
    ]),
    caracteristicas: "Presencia amplia en UY/AR/BR. Referencia para campos que buscan soluciones completas con apoyo técnico y continuidad de abastecimiento.",
  }),
  buildFicha({
    nombre: "Virbamec",
    laboratorio: "Virbac.",
    principio_activo: "Ivermectina.",
    presentacion: "Inyectable SC 1% y/o pour-on según país.",
    via_administracion: "Subcutánea y tópica.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "35 a 49 DIAS.",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Endectocida para nematodos gastrointestinales y pulmonares sensibles.",
      "• Dosis orientativa 1%: 200 mcg/kg.",
      "• Incluye acción sobre ectoparásitos de relevancia productiva.",
      "• Aplicar en calendarios estratégicos definidos por riesgo.",
      "• Conservar en envase original y evitar exposición solar.",
    ]),
    caracteristicas: "Comercializado en UY/AR/BR como alternativa de ivermectina de marca reconocida. Se integra fácilmente en planes sanitarios de cría e invernada.",
  }),
  buildFicha({
    nombre: "Zactran",
    laboratorio: "Merck Animal Health/MSD.",
    principio_activo: "Gamithromicina.",
    presentacion: "Solución inyectable 150 mg/mL.",
    via_administracion: "Subcutánea.",
    especie: "Bovinos",
    tiempo_espera_carne: "35 DIAS (referencia habitual).",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS LECHERAS EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Macrólido azalido para tratamiento de enfermedad respiratoria bovina.",
      "• Activo frente a Mannheimia, Pasteurella e Histophilus sensibles.",
      "• Dosis estándar: 6 mg/kg en dosis única SC.",
      "• Adecuado para protocolos de intervención rápida en lotes de riesgo.",
      "• Mantener manejo responsable por tratarse de antimicrobiano crítico.",
    ]),
    caracteristicas: "Disponible en UY/AR/BR. Herramienta terapéutica de dosis única muy valorada en feedlot y recría por practicidad operativa.",
  }),
  buildFicha({
    nombre: "Zoetis",
    laboratorio: "Zoetis, laboratorio líder global en salud animal.",
    principio_activo: "Líneas de antiparasitarios, antimicrobianos, AINE y vacunas.",
    presentacion: "Inyectables, orales, pour-on y biológicos.",
    via_administracion: "SC, IM, oral y tópica según línea.",
    especie: "Bovinos y Ovinos",
    tiempo_espera_carne: "SEGUN PRODUCTO DE LINEA.",
    tiempo_espera_leche: "SEGUN PRODUCTO; varias líneas específicas para tambo.",
    detalles_tecnicos: joinLines([
      "• Portafolio de referencia para BRD, control parasitario y bienestar animal.",
      "• Incluye marcas ampliamente adoptadas en sistemas de carne y leche.",
      "• Protocolos deben definirse por categoría, riesgo y estacionalidad.",
      "• Integra prevención, tratamiento y trazabilidad sanitaria.",
      "• Requiere cumplimiento estricto de conservación por producto.",
    ]),
    caracteristicas: "Muy fuerte en UY/AR/BR con alta capilaridad comercial. Elección frecuente para planes sanitarios integrales con respaldo técnico y evidencia de campo.",
  }),
  buildFicha({
    nombre: "Zuprevo",
    laboratorio: "MSD/Merck Animal Health.",
    principio_activo: "Tildipirosina.",
    presentacion: "Inyectable 180 mg/mL.",
    via_administracion: "Subcutánea.",
    especie: "Bovinos",
    tiempo_espera_carne: "47 DIAS (valor de referencia frecuente).",
    tiempo_espera_leche: "NO AUTORIZADO EN VACAS LECHERAS EN ORDEÑE.",
    detalles_tecnicos: joinLines([
      "• Macrólido de acción prolongada para enfermedad respiratoria bovina.",
      "• Eficaz frente a bacterias clave del complejo respiratorio.",
      "• Dosis orientativa: 4 mg/kg en dosis única SC.",
      "• Uso frecuente en metafilaxia de lotes con alto desafío sanitario.",
      "• Aplicar bajo diagnóstico y plan de uso prudente de antimicrobianos.",
    ]),
    caracteristicas: "Comercializado en UY/AR/BR para control de BRD en sistemas intensivos y semiextensivos. Permite manejo práctico de lotes con menor número de intervenciones.",
  }),
];
